### ISSUE TITLE
seed get 密码输入错误时，返回信息有误

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#106]
![image](https://user-images.githubusercontent.com/44956625/49435966-d73c4e00-f7f2-11e8-806c-6e30617bcb55.png)
seed get 密码输入错误时，返回信息有误，应提示密码错误

**Comment by vipwzw** [comment]
wallet 相关的 issues 可以放到 chain33

**Comment by xies1031** [comment]
OK

**Comment by vipwzw** [comment]
33cn/chain33#153
