### ISSUE TITLE
evm合约转账操作实现冻结能力

### ISSUE THREAD

**Issue by litian33** [33cn/plugin#108]
目前用户操作EVM合约时，是先转账到自己地址下的合约账号，然后在合约操作时再转到evm自己合约实例地址下；

其中，第二步操作不可靠，如果此地址被攻破，所有钱将丢失，所以需要修改成使用frozen机制冻结在自己的合约账户，等合约操作完成后再进行转账操作；

@vipwzw  @zhengjunhe @andyYuanFZM

**Comment by litian33** [comment]
## ICO模式
|序号|转账方|接收方|存放地址|说明|
|-|-|-|-|-|
|1|user|contract|creator:contract (frozen)|用户参与募资，冻结在合约创建者的合约地址下|
|2|creator|contract|creator:contract (frozen)|合约创建者自己参与募资（神经质操作），冻结在合约创建者的合约|地址下|
|3|contract|creator|creator:contract (active)|合约创建者（ICO发起人），提取募集资金|
|4|contract|user|user:contract (active)|ICO合伙人提取资金|

> 后两步骤的操作权限在ICO合约内部控制；

## Game模式

|序号|转账方|接收方|存放地址|说明|
|-|-|-|-|-|
|1|user|contract|creator:contract (frozen)|用户参与游戏，冻结在合约创建者的合约地址下|
|2|creator|contract|creator:contract (frozen)|合约创建者自己参与游戏，冻结在合约创建者的合约地址下|
|3|contract|creator|creator:contract (active)|合约创建者，提取游戏池资金|
|4|contract|user|user:contract (active)|游戏赢家接收游戏奖金|

> 后两步骤的操作权限在游戏合约内部控制；

## 处理机制

从上面的对比分析，得知ICO模式和游戏合约模式处理机制相同，下面分别说明对应操作的系统处理步骤；

|序号|处理步骤|
|-|-|
|1|首先将钱转到创建者合约地址下：<br/> step1: ExecTransfer(user, creator, contract, amount) <br/> 然后进行冻结：<br/> step2: ExecFrozen(creator, contract, amount) |
|2| 在创建者合约地址下冻结金额：<br/>ExecFrozen(creator, contract, amount)|
|3| 从创建者合约地址下冻结的钱中解冻：<br/> ExecActive(creator, contract, amount)|
|4| 从创建者合约地址下冻结的钱中转出到用户合约地址：<br/> ExecTransferFrozen(creator, user, contract, amount)|

之所以没有将钱直接冻结到用户自己的合约地址，是因为这种方式只适用于游戏模式，无法解决ICO募资的模式；

按照本方案改造后，虽然用户向合约转的钱，冻结在了创建者的合约地址，但是创建者自己是没有权限把这个钱取出来的，只能通过合约进行操作，所以不存在安全问题；

另外，在ICO模式下，合约中会有逻辑控制某些地址有权限从合约中提钱，这种情况下从创建者合约地址中冻结的钱中向这些地址转账是合法逻辑，系统不会进行限制；

**Comment by vipwzw** [comment]
创建者合约 和 用户合约地址 表达的是什么意思？

**Comment by vipwzw** [comment]
我的理解是不是，evm 合约 和 普通合约的操作可以相同。可以通过 solidity 代码来操作 我们的账户资产是不是更加合理。相当于，evm 内置一个操作账户的类或者函数。不过这样的话，可能要对编译器 或者 虚拟机做一定的修改。

**Comment by vipwzw** [comment]
send to  ExecAddress("user.evm.") 代表frozen 操作
send to user address 表示 active
我的理解有问题吗？

在以太坊中，这个应该是一个 0x1234... 这样的地址吧，写合约的时候
不是我们bty的地址
就是用某些特殊的地址表示 frozen操作
甚至可以用更加复杂的地址编码更加复杂的操作
比如 0x0000  表示 frozen
ox0001 表示直接扣除前
0x0002 表示加钱

然后我们再包装一个 lib 给用户调用

在用户看来 就是调用 ExecFrozen ExecActive 类似的操作了。

这样不知道是否可行
