### ISSUE TITLE
【autonomy】社区自治参数修改冲突

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#1083]
新修改社区自治合约中，将全体持票人赞成率修改为可修改项，范围为50%-80%，该参数需要与全体持票人否决率保持联动。
![8625f2b23bf5e73c57c2e26f86e0baa](https://user-images.githubusercontent.com/44956625/139229142-494e7f0f-1166-4867-aadf-10b4920c40f1.png)
旧版规则如上图。新版修改后若将赞成率下调至50，否决率仍保持33不变，则在投票时出现50赞成50反对的情况时，提案通过与否矛盾。
@YingQm

**Comment by YingQm** [comment]
对于大项目，则董事会成员通过之后，进入公示期，公示期期间（默认一周的区块高度），全体持票人可以对该项目投否决票，超过33%的全体持票人投否决票，则该提案视为不通过

**Comment by YingQm** [comment]
投票通过后，公示期内投反对票，所以是不矛盾的
