### ISSUE TITLE
【autonomy】合约相关问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#1087]
1.旧版本查询现有规则时，未显示全民投票参与率（pubAttendRatio）及赞成率（pubApproveRatio）；
![image](https://user-images.githubusercontent.com/44956625/140035564-f4a23be3-baba-49ab-977f-39128552ec95.png)

2.发起提案进行董事会成员投票时，计算赞成率未减去弃权票，如下图，共21票，其中16票弃权，3票赞成，1票反对，赞成率应为75%，高于所需53%，但提案仍未通过
![image](https://user-images.githubusercontent.com/44956625/140035793-5d894e3d-1da7-48ee-a63b-f7f34279519b.png)
![image](https://user-images.githubusercontent.com/44956625/140035843-bda4e657-9640-4b36-8202-0f2e5b11adf5.png)
@YingQm

**Comment by xies1031** [comment]
voteChange时赞成率也未去掉弃权票

**Comment by xies1031** [comment]
3.提案董事会成员计算赞成率时错误，如图，赞成票2.6w，弃权票3.8W，总票数为12.2w，赞成率及参与率需求50%，此时赞成率计算为2.6/12.2-3.8，达不到50%的要求，但是该提案通过了
![image](https://user-images.githubusercontent.com/44956625/140039927-5c16e207-a599-4726-9878-38f12377f3ee.png)
![image](https://user-images.githubusercontent.com/44956625/140039950-88c1d332-1ae9-454d-abaa-65b69fb331d1.png)

**Comment by YingQm** [comment]
#1089
