### ISSUE TITLE
plugin代码将钱包锁定后，依然可以挖矿

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#109]
plugin代码将钱包锁定后，依然可以挖矿
![image](https://user-images.githubusercontent.com/44956625/49507313-2b126a00-f8bb-11e8-8879-a1f469b445aa.png)
锁定于18:15
![image](https://user-images.githubusercontent.com/44956625/49507349-3f566700-f8bb-11e8-808d-ba96629a6156.png)
该地址依然可以挖矿，但无法open和close

**Comment by icehawk-hyb** [comment]
1，看代码实现是 close和open的交易是在wallet模块这边签名，所以钱包锁和挖矿锁都关闭后关票和买票交易都没法签名。
2，miner交易是在ticket共识模块直接构造并签名，不需要校验钱包的锁，在买完票之后，挖矿地址的对应私钥都会保存在ticket共识模块的。
3，ticket共识代码实现有一个1小时的定时刷票的接口，如果钱包的所有锁都是锁住的话，此时就不能从钱包获取ticket信息，此时ticket共识模块就会将 本模块tickets信息都设置成nil，不能再继续挖矿。

4.结论：在钱包锁和挖矿锁都关闭1小时后，ticket共识模块才会停止挖矿。

**Comment by icehawk-hyb** [comment]
关闭钱包的自动挖矿功能看看ticket共识是不是还在继续出矿 @xies1031

**Comment by xies1031** [comment]
最新修改后的代码同步时panic
![image](https://user-images.githubusercontent.com/44956625/49724111-840b4500-fca3-11e8-8d37-b72cc940a4f2.png)
