### ISSUE TITLE
区块链上的数据发布合约实现

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#111]
需求背景：
为保证数据的公平公正性，在区块链上提供权威数据发布合约。满足以下需求：
1.  合约提供录入和查询接口。
2.  合约录入时对数据的key和value定义好标准的格式。
3.  合约是否要满足一定的经济模型，惩罚机制（一期可以不实现，后面再加入）

实现点：
1.  发布者的地址需要通过superManager添加，调用我们系统manage合约。
2.  数据发布的key要遵循一定的格式，比如游戏类的格式要满足一定的前缀（发布者地址+ 运营特征值+游戏类别 等）
3.  数据发布的时候要能输入数据来源描述（比如：数据来源于新浪体育）
4.  数据发布的 value要根据现有的业务做一定的抽象，这块一期可以先考虑下，不用实现的很完备。 一期可以用json格式，数据提供方和开发方可以事先先约定好。
5.  合约对外提供查询接口供具体的应用合约调用， 具体的应用合约只查询满足条件的key，获取数据做相应的运算。
6.  数据的发布需要先预发布，再审核后切换成正式发布。（类似于token的预创建和完成这两步）

**Comment by Hugo-Huang** [comment]
好的

**Comment by Hugo-Huang** [comment]
@andyYuanFZM 参考token的处理，建议在预发布与正式发布之间增加撤销预发布接口，允许发布者撤销之前的预发布。

**Comment by Hugo-Huang** [comment]
@andyYuanFZM 跟 @zzh33cn 讨论了一下当前该合约的应用场景，目的主要是提供给第三方一个类似预言机的能力，即发布问题，发布结果(包括发布随机数等)，查询结果的能力。这样关于问题结果的预发布，审核发布结果，撤销预发布这样的中间阶段放在第三方内部处理比较合适，不适宜将中间结果也写到区块链上，你看这样设计是不是更合理些？

**Comment by Hugo-Huang** [comment]
@andyYuanFZM 鉴于直接发布问题结果不利于对问题的跟踪，建议增加发布问题的接口，这样起到预告作用，便于对关注的问题跟踪，也可以撤销发布的问题。

**Comment by zzh33cn** [comment]
根据大家讨论的结果，梳理了一下流程和状态机，放在这里：https://gitlab.33.cn/richardzhang/share/blob/master/%E6%95%B0%E6%8D%AE%E5%8F%91%E5%B8%83%E9%A2%84%E8%A8%80%E6%9C%BA%E5%90%88%E7%BA%A6.md

**Comment by 33cn** [comment]
oracle 合约
