### ISSUE TITLE
实现类fomo3D 游戏合约

### ISSUE THREAD

**Issue by harrylee2015** [33cn/plugin#112]
## 1.1 背景
类Fomo 3D游戏，满足以下几个要求：
- 可以短时间结束游戏，尽量不让游戏时间拖太长；
- F3D的核心思想不变，最后一把钥匙拿大奖；
- 早起参与者拥有相对优势；
- 游戏多轮长期运转，避免Fomo3D一轮终结的命运；

## 1.2 游戏设计
原版F3D的游戏机制比较复杂，一般参与人也很难搞清楚，所以本游戏设计尽量简单易懂，使参与者可以快速理解游戏玩法，及时参与。

下面分别从几方面介绍游戏的设计组成，然后再统一汇总下游戏的玩法及运作机制。

### 1.2.1 奖金分配
一轮游戏过程中不进行任何分配，一轮结束后，以所有募集到的金额为基础，按以下比例进行分配：
这里比例应该可动态调整
|比例|用途|说明|
|-|-|-|
|40%|终极大奖|奖励给最后一把钥匙持有人|
|30%|持有分红|本轮游戏的所有钥匙持有人按比例分红|
|20%|奖金池|滚动到下一轮的奖金池，作为下一轮的初始金额|
|10%|平台运营|平台运营费用|

如此设计的意图是，保留最后一把钥匙吸引力的同时（40%奖励），给予其他参与人分红鼓励（30%高比例分红），并且吸引下一轮玩家尽早参与（初始奖金池有上一轮的20%金额，早期钥匙有超高性价比）；

### 1.2.2 钥匙价格
> 使用统一的游戏代币，目前和BTY一比一兑换

第一把钥匙的初始价格：0.1 Token；

~~下一把钥匙的价格，在上一把成功交易价格基础上，上浮1%，即第二把钥匙价格为0.0101；~~

下一把钥匙的价格，在上一把成功交易价格基础上，固定上浮10%；

以此类推；

~~钥匙价格上浮范围，用户可控，幅度为：1%-10%；~~

如果一次购买多把钥匙，则多把钥匙的价格相同，也不会因为上一个人买了多把而影响下一个人买钥匙的价格；

---
**同一个区块内，如何判定交易的先后并且使用不同的钥匙价格？多人同时购买时价格如何确定？**

使用下面几点，保证可以正常运行：

~~1. 后台提供缓存接口，实时更新最后一把钥匙价格；~~
~~1. 游戏界面实时调用后台接口，刷新前端钥匙价格，并在界面提示价格仅供参考，可能会有小幅上浮；~~
~~1. 参与者购买钥匙时，仅提供钥匙把数、上浮比例，不提供钥匙的价格，实际价格由合约在执行时计算；~~
~~1. 游戏合约执行时，实时在缓存数据库中更新钥匙价格，以保证同一个区块内的多笔交易可以按顺序、钥匙价格递增的方式执行；~~

1. 同一个区块内，钥匙的价格不变，如果本区块有人购买钥匙，则下一个区块钥匙价格发生变化；

**异常情况：**

1. 有可能出现参与者余额不足的情况（界面显示余额足够，合约执行时不足），此时交易会失败；

### 1.2.3 游戏周期
本游戏一轮的运行时间为1小时，如果无人购买钥匙，则剩余时间会实时减小，如果有人购买钥匙，则可以延长剩余时间，但最大剩余事件仍然不会超过1小时；

|项|值|说明|
|-|-|-|
|初始时间|1小时||
|一把钥匙延长|30秒|一个账户购买多把钥匙，最多延长300秒|
|最大可用时间|1小时|延长时间+剩余时间 <= 1小时|

#### 1.2.3.1 游戏合约中的计时器逻辑
需要在游戏平行链节点上运行一个定时检测程序，以30秒为周期，检测游戏的结束时间，当游戏结束后发送一个开奖交易，进行开奖； 
定时检测程序可以优化如下：

|剩余时间|下一检测周期|
|-|-|
|>10分钟|10分钟|
|>5分钟|1分钟|
|>1分钟|30秒|
|<1分钟|10秒|

### 1.2.4 异常情况处理
游戏在运行过程中，可能会出现一些异常情况，需要有对应的处理机制可以保证游戏正常运转下去；

#### 1.2.4.1 一轮周期内，无人参与游戏
> 游戏运行初期用户量较少，或夜间时，可能会出现这种情况

此种情况下，一轮游戏周期照常结束，奖金池100%全量转移到下一轮初始奖金池；

#### 1.2.4.2 开奖交易和购买最后一把钥匙的交易同时到达
> 因为区块链系统并不记录交易发生或接收的时间，而一个交易的有效期又是客户可控的，所以需要一种机制即可以判断交易发生的时间，又可以防止参与者作弊获得奖金。

- 游戏开始时间：

    游戏开始交易打包区块的时间；

- 游戏结束判断：

    游戏开奖交易中处理，检测到上一区块的打包时间和本轮游戏中最后一个Key交易区块的打包时间间隔大于1小时；

> 因为定时处理机制，无法保证游戏精确到秒级开奖，所以，可能会出现1个小时的周期已经结束，但是还没有开奖，此时，如果再有买入钥匙的交易进入怎么处理？

游戏合约应当将此交易作为非法交易处理，以保证最后一把钥匙持有人的权益；

> 如果开奖交易和购买钥匙的交易在统一个区块内，开奖交易在前，购买钥匙的交易如何处理？

购买交易中应当包含本轮游戏的轮次数据，因为开奖交易在前，相当于本轮已经结束，购买交易也作为失败处理；

### 1.2.5 限制

- 游戏开始交易、开奖交易，必须由指定地址发出，其它均为非法；
- 因为游戏周期判断的需要，区块打包时间间隔不能太长，建议15秒；

**Comment by vipwzw** [comment]
打包时间无法预测，可能会比较久，几分钟也是有可能的。

**Comment by vipwzw** [comment]
看上去这个游戏也不错，挺好玩

**Comment by harrylee2015** [comment]
[新增F3D合约具体存储结构设计](https://github.com/harrylee2015/share/blob/master/chain33/f3d%E5%90%88%E7%BA%A6%E8%AE%BE%E8%AE%A1.md)

**Comment by harrylee2015** [comment]
开发进展：已用工具生成模版本格式，下周填充具体业务逻辑
[F3D合约代码开发分支](https://github.com/harrylee2015/plugin/tree/f3d)

**Comment by harrylee2015** [comment]
基本业务逻辑代码已经完成，剩下封装对外的查询接口

**Comment by harrylee2015** [comment]
明天可以进入测试阶段了

**Comment by harrylee2015** [comment]
[测试样例](https://github.com/harrylee2015/share/blob/master/chain33/F3D_test.md)

**Comment by harrylee2015** [comment]
f3d代码暂时闭源
