### ISSUE TITLE
平行链重新搭建之后之前节点的里面的地址怎么同步过来？

### ISSUE THREAD

**Issue by nancyxu1982** [33cn/plugin#1143]
原来的节点过期无法运行，因此购买了新的服务器，创建新的节点，创建新的节点的步骤如下：
1.  下载平行链代码
2. 修改配置行链配置文件
3. 启动平行链，等待数据同步成功
4. 使用postman导入平行链seed
5. 使用postman导入创世地址的私钥
6. 调用Chain33.WalletTxList接口成功
curl --location -g --request POST '{{chain_url}}:8901' \
--data-raw '    {
        "jsonrpc":"2.0",
        "id":0,
        "method":"Chain33.WalletTxList",
        "params":[{"fromTx":"","count":10,"direction":0}]
    }'

7. 发送交易
   CreateRawTransaction调用没有问题
    curl --location -g --request POST '{{chain_url}}:8901' \
    --header 'Content-Type: text/plain' \
    --data-raw '{
        "jsonrpc":"2.0",
        "id":1,
        "method":"Chain33.CreateRawTransaction",
        "params":[
            {
                "to":"1AJccUkd......qAAzKQ",
                "amount":10000000,
                "fee":0,
                "note":"first test",
                "isToken":false,
                "execer":"coins" 
            }
        ]
    }'
   Chain33.CreateNoBalanceTransaction调用提示错误， **返回错误：ErrAddrNotExist**
   curl --location -g --request POST '{{chain_url}}:8901' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "jsonrpc":"2.0",
  "id":1,
  "method":"Chain33.CreateNoBalanceTransaction",
  "params":[
    {
        "txHex":"0x0a05636f696e73123918010a351080ade2041a0a66697273742074657374222231414a6363556b64745a3871694b7874454c4b356d72664c7851436f7141417a4b5120......e3a22314761485970576d71414a7371527772706f4e6342385676674b7453776a63487174",
        "payAddr":"1FdiWH5VDA564eU......yM4GDaZqKS2P",
        "expire":"30s"
    }
  ]
}'

那么现在的问题是：原来节点里面的存在的地址，怎么同步过来？

**Comment by libangzhu** [comment]
不是已经说了，你怎么不看回答吗

**Comment by libangzhu** [comment]
调用提示错误， 返回错误：ErrAddrNotExist 说明你连接的这个节点的钱包里并没有这个地址，你先确认下这个地址是从哪里来的

"payAddr":"1FdiWH5VDA564eU......yM4GDaZqKS2P",
并不是你导入seed之后，地址就会自动创建好，请先确定这个地址的来源，如果你有此地址的私钥，那就直接导入该地址的私钥

**Comment by libangzhu** [comment]
导入 seed之后，需要创建地址的话，可以调用相关创建地址接口，来恢复seed 对应的地址

**Comment by nancyxu1982** [comment]
节点创建好之后，地址是不能自动跟过来的么？如果我想将原来那个过期的节点创建的地址放到这个新的节点里面，要怎么做？

**Comment by libangzhu** [comment]
> 

https://chain.33.cn/document/94#1.5%20%E5%88%9B%E5%BB%BA%E8%B4%A6%E6%88%B7%20NewAccount

**Comment by nancyxu1982** [comment]
这个只是创建新的地址
原来这个钱包里面有的地址，怎么同步呢？

**Comment by libangzhu** [comment]
> 这个只是创建新的地址 原来平行链的节点里面所有地址，可以同步么？怎么同步？
你说的是恢复平行链的数据吧，那你得用之前部署的平行链的配置的参数来恢复，
如果你们还有当时对应的配置参数，之前有跟我们运营有关合作，具体的请找我们运营来处理

**Comment by nancyxu1982** [comment]
> 这个只是创建新的地址 原来平行链的节点里面所有地址，可以同步么？怎么同步？
> 你说的是恢复平行链的数据吧，那你得用之前部署的平行链的配置的参数来恢复，
> 如果你们还有当时对应的配置参数，之前有跟我们运营有关合作，具体的请找我们运营来处理

我的和之前参数是一样的，但是数据一直没有恢复呀，所以想问问怎么处理？

**Comment by libangzhu** [comment]
这里三两句说不清，请找我们的人对接吧
