### ISSUE TITLE
测试链偶发ErrCheckTxHash错误

### ISSUE THREAD

**Issue by 2066632394** [33cn/plugin#1192]
单节点挖矿+一个同步节点
间隔几千，几万，十几万都出现过ErrCoinBaseTicketStatus错误，同时导致同步节点出现ErrCheckTxHash错误
挖矿节点后续正常一直出块，同步节点不同步
只有挖矿节点回滚到错误区块之前，同步节点才恢复正常同步

**Comment by bysomeone** [comment]
#### TxHash错误初步分析

通过几次区块原数据提取， 挖矿节点计算的block TxHash是错误的，导致同步节点高度无法增长，可能和ticket相关逻辑有关

**Comment by bysomeone** [comment]
1. 测试链配置的ticket 挖矿周期很短(成熟/冻结等时长),  后台生成ticket交易的处理定时器间隔需要同步调整, 否则产生的ticket交易, 状态不一致导致执行失败

2. 代码写死的定时间隔, 需要配置化
