### ISSUE TITLE
用户合约log类型的定义有和系统日志冲突的可能性

### ISSUE THREAD

**Issue by zhengjunhe** [33cn/plugin#127]
因为当前每个合约是分而自治的，对于日志的解析一般情况是不会冲突的，
但是前提是，日志编号没有与系统日志号有冲突的情况，
即不占用以下日志编号：
TyLogReserved = 0
	TyLogErr      = 1
	TyLogFee      = 2
	//TyLogTransfer coins
	TyLogTransfer        = 3
	TyLogGenesis         = 4
	TyLogDeposit         = 5
	TyLogExecTransfer    = 6
	TyLogExecWithdraw    = 7
	TyLogExecDeposit     = 8
	TyLogExecFrozen      = 9
	TyLogExecActive      = 10
	TyLogGenesisTransfer = 11
	TyLogGenesisDeposit  = 12

但是目前没有，软件行为可以控制用户合约不定义以下系统编号，
可能需要写完代码调试的时候，发现日志解析错误了，就像系统日志用
用户合约日志格式在解析，因为默认是优先使用用户合约日志格式解析，
所以我觉得当前我们需要一种机制，帮助用户合约开发者规避以上问题，
系统占用的日志号不能被用户合约用来注册日志号，可以让其直接panic，
然后给出信息，提示注册的日志号占用了系统日志号。
因为当前合约都是之前统一编号，后来在重构过程中直接拷贝过去了，
没有发生这种情况

**Comment by zhengjunhe** [comment]
@vipwzw 你认为呢？

**Comment by 33cn** [comment]
可以移动到 33cn/chain33

**Comment by 33cn** [comment]
logmap 可以做一个判断，如果和 SystemLog 重复，那么直接panic 提示。

**Comment by 33cn** [comment]
建议用户的log 从 10000 开始
