### ISSUE TITLE
evm 客户端创建合约参数应该支持从文件读取 abi bin

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#129]
真实的合约可能abi bin 很大， 直接放在在参数里把内容写上，用起来不方便
$ ls 1.abi  1.bin  -lh
-rw-rw-r-- 1 linj linj 12K 12月 11 16:19 1.abi
-rw-rw-r-- 1 linj linj 24K 12月 11 16:18 1.bin

**Comment by 33cn** [comment]
@linj-disanbo  @litian33 可以考虑整合一个 solc 编译器命令行。和我们的cli 深度互动，直接可以通过：
chain33-cli evm create --sol "token.sol" --name "hello" ...  类似这样的方式部署合约.

参考以太坊的实现：

https://github.com/ethereum/go-ethereum/blob/1064e3283db6e388db4fc353c8bd17b57d57fa42/common/compiler/solidity.go

**Comment by andyYuanFZM** [comment]
@lynAzrael  这个问题看一下。

**Comment by lynAzrael** [comment]
好的

**Comment by 33cn** [comment]
其实 对用户来说寻找 solc 的编译器 可能还是比较麻烦，可以考虑提供一下 mac linux windows 三个版本的下载链接。编译好了以后，可以放到我们的阿里云 文件服务器上去

**Comment by lynAzrael** [comment]
@33cn 好的。
