### ISSUE TITLE
plugin代码ticket open和close时出现重复交易

### ISSUE THREAD

**Issue by flyaway53** [33cn/plugin#15]
1.调用cli wallet auto_mine -f 1进行购票并open
2.调用cli wallet auto_mine -f 0 关闭自动购票后再cli ticket close关闭选票
以上两种ticket相关的操作会造成重复交易
![image](https://user-images.githubusercontent.com/28993758/48465516-fa8c6280-e81d-11e8-8404-199602f4e586.png)
![image](https://user-images.githubusercontent.com/28993758/48465533-0f68f600-e81e-11e8-81c4-26eef173cacd.png)

**Comment by vipwzw** [comment]
重复挖矿的问题没有解决。

**Comment by vipwzw** [comment]
@chain33-shg  这个问题继续保持关注

**Comment by vipwzw** [comment]
目前有一种情况是会重新 open，比如 returnaddress 和 mineraddress 的私钥都在钱包里面。这样的情况会重复打开，其他的情况都应该是bug

**Comment by chain33-shg** [comment]
- 在buyTicket中添加日志进行问题追踪
```
bizlog.Info("ticketPolicy buyTicket begin")
// ....
bizlog.Info("ticketPolicy buyTicket", "Address", address.PubKeyToAddress(priv.PubKey().Bytes()).String(), "txhash", hex.EncodeToString(hash), "n", n)
// ...
bizlog.Info("ticketPolicy buyTicket end")
```

- 在buyMinerAddrTicket添加日志进行问题追踪
```
bizlog.Info("ticketPolicy buyMinerAddrTicket begin")
// ... 
bizlog.Info("ticketPolicy buyMinerAddrTicket", "Address", address.PubKeyToAddress(priv.PubKey().Bytes()).String(), "n", n)
// ...
bizlog.Info("ticketPolicy buyMinerAddrTicket end")
```

**Comment by chain33-shg** [comment]
节点挖矿时设置的minerAddress和returnAddress均为1K7Fko7e21F2qXdYriVLheJue5ZW5KerZL， 并且通过ticket bind_miner绑定了1K7Fko7e21F2qXdYriVLheJue5ZW5KerZL地址。

这样操作以后，在节点进行Open、Close时，会因为在线地址和离线地址均是同一个地址，所以会同时创建两个交易。这两个交易在被执行时因为扣除了余额导致另一个交易因为余额不足而执行失败，从而导致本问题的发生。

正确的做法应该是要么不使用离线挖矿功能，如果需要离线挖矿，则绑定地址不能与挖矿地址一样。

**Comment by vipwzw** [comment]
OK
