### ISSUE TITLE
离线挖矿时，离线地址无法关闭已授权的票

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#156]
离线地址A授权给在线地址B挖矿，在遗失地址B的私钥后，cli中无法使用地址A的私钥关闭由地址Bopen的票。
重新给地址C授权后，C地址也没有权限关闭这部分的票。

**Comment by 33cn** [comment]
添加一个函数，CloseTicketsByReturnAddr

**Comment by 33cn** [comment]
rpc, cli 配套
