### ISSUE TITLE
平行链是否可以固化一个最小化的配置

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#171]
刚刚更新了下最新的plugin代码， 然后用之前的平行链配置启动。 出现mempool模块找不到对应的cfg而panic。  是由于mempool有新功能合入导致的，规避方法是把mempool新增加的配置贴到平行链的配置文件中。

但是对于平行链来说，它实际并不会用到mempool的功能，所以在它的配置文件中增加这块配置，会对使用者造成一定的困扰。 

所以是不是针对平行链，固化一份最简配置，除非影响到平行链功能了，配置才可以做升级。

**Comment by vipwzw** [comment]
这个问题可以通过这样的方式解决：util/cli/chain33.go 中，在平行链的情况下，不要启动 P2P 和 mempool
来实现，只启动必要的模块。
