### ISSUE TITLE
平行链上增加cli查询功能，查看和主链的同步状态

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#172]
目前平行链同步主链区块时，没有很好的办法查询同步的状态。  
现在的做是是结合 cli block last_header查看区块的增长，以及log的打印来判断平行链是否已经追上主链的高度。

最好能增加一个cli的查询命令，可以判断平行链有没有追上主链。

**Comment by harrylee2015** [comment]
复用net 命令

``` bash
harry@harry-VirtualBox:~/parachain$ ./chain33-cli net is_sync  --rpc_laddr http://localhost:8901
true

```

**Comment by harrylee2015** [comment]
@vipwzw  我发现para consensus 和 paracross 执行器注册名称不一样，因为chain框架中有地方用了”para" 这个名字，为了保险起见，我没做修改，调用QueryConsensusFunc()时，是同consensus 时一样，填“para" ，你看这个后面是不是需要统一整改一下
