### ISSUE TITLE
在平行链同步时， 报错

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#173]
**Describe the bug**
在平行链同步时， 报错
```
EROR[12-19|08:03:55] isAllowLocalKey prefix last char is not '-' module=execs key=LODB-paracross-titleVoteHeight-user.p.para.-000000000215 exec=user.p.para.paracross minkeylen=27
```

**Expected behavior**
同步成功， 不报错

**Comment by vipwzw** [comment]
应该是chain33 不是最新的，在最新的chain33上，这个测试可以过。
![image](https://user-images.githubusercontent.com/1617585/50414912-26eec200-0853-11e9-9674-6070f1896e2d.png)

**Comment by linj-disanbo** [comment]
看到代码， 是第二次检测通过了。
