### ISSUE TITLE
小幸运抽奖游戏合约

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#178]
游戏设计：
https://gitlab.33.cn/litian/share/blob/master/chain33/Feel%20Lucky.md

**Comment by andyYuanFZM** [comment]
@lynAzrael 看一下这个功能

**Comment by lynAzrael** [comment]
@andyYuanFZM 好的

**Comment by lynAzrael** [comment]
[flucky抽奖游戏合约实现细节设计](https://github.com/lynAzrael/L/tree/master/chain33_plugin/flucky)

**Comment by lynAzrael** [comment]
[代码开发分支](https://github.com/lynAzrael/plugin)
基本逻辑已经完成，后续补充随机数生成、投注信息批量查询接口以及外部rpc查询接口的封装

**Comment by lynAzrael** [comment]
开发完成且基础功能测试完毕
[测试用例](https://github.com/lynAzrael/L/blob/master/chain33_plugin/flucky/test/Flucky_test.md)

**Comment by lynAzrael** [comment]
使用测试工具进行批量测试
[测试工具](https://github.com/lynAzrael/L/tree/master/chain33_plugin/flucky/scripts)

**Comment by andyYuanFZM** [comment]
第一期功能完成。代码暂不开源。
