### ISSUE TITLE
paracross币，需要提供余额查询接口

### ISSUE THREAD

**Issue by harrylee2015** [33cn/plugin#190]
试了一下跨链功能，目前还不支持paracross币余额查询
遇到问题，也不知道如何定位
下面是查询coins 在相应合约地址下的余额
```bash
harry@harry-VirtualBox:~/parachain$ ./chain33-cli --rpc_laddr http://localhost:8901 account balance -a "16ReZHzMCGtPt8B7XbnZQ2jeXsPG9wEufh" -e paracross  --paraName user.p.evmtest.
{
    "balance": "0.0000",
    "frozen": "0.0000",
    "addr": "16ReZHzMCGtPt8B7XbnZQ2jeXsPG9wEufh"
}
```

**Comment by vipwzw** [comment]
可以找 @linj-disanbo

**Comment by vipwzw** [comment]
目前只有测试链支持跨链转账

**Comment by harrylee2015** [comment]
跨链转账有分叉高度设置吗？自己的搭的链不可以吗？都是最新代码编出来的，主链平行链都是最新代码

**Comment by vipwzw** [comment]
没有设置分叉高度

**Comment by linj-disanbo** [comment]
添加了 asset balance 命令可以查询。 
$ docker exec  build_chain33_1 /root/chain33-para-cli asset balance -a 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv --asset_exec paracross  --asset_symbol coins.bty -e user.p.para.trade
{
    "balance": "0.0001",
    "frozen": "0.0000",
    "addr": "12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
}

命令行有bug， 需要等待 https://github.com/33cn/plugin/pull/214 修复
