### ISSUE TITLE
平行链执行器执行时候，需要提供主链对应区块的hash值

### ISSUE THREAD

**Issue by 33cn** [33cn/plugin#191]
#184 中，平行链执行的情况下，如果无法获取对应的hash执行，去主链获取到的区块可能会和平行链当前区块不同。

**Comment by mdj33** [comment]
讨论的结果是，平行链当前lottery合约计算随机数的tx应该能获取到同一个块里面的miner tx，而不是上一个块的 miner tx， 这样就没有获取平行链上一个块不安全的问题， 可以直接从miner tx里面获取对应主链区块的hash，只是这个地方代码框架方面可能要稍微做些修改，就是一个合约可以获取非当前合约的tx信息

**Comment by mdj33** [comment]
当前框架里面在一个执行器执行的时候已经可以获取到区块里面的所有的txs，也可以获取到miner tx解析

**Comment by mdj33** [comment]
@jixingwei  @vipwzw   当前框架已经提供了所有tx，也可以获取到miner tx的hash，这个issue不需要新的改进  close
