### ISSUE TITLE
plugin同步时打印乱码

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#208]
**Describe the bug**
win环境用最新plugin代码同步时打印信息出现乱码

**Screenshots**
![image](https://user-images.githubusercontent.com/44956625/50762181-39331c00-12a7-11e9-96c5-b6c999092858.png)

**Comment by xies1031** [comment]
ubuntu下也存在
![image](https://user-images.githubusercontent.com/44956625/50765569-3e956400-12b1-11e9-8bc2-0b1a62686f84.png)

**Comment by Hugo-Huang** [comment]
@vipwzw 上次提交(b9e80d5430c10d1f1afc52a995b68624906c7482)时在chain33/system/store/base.go文件的113和123行增加的打印信息,直接用string打印会显示乱码，可以改成common.ToHex或者去掉打印信息。

**Comment by vipwzw** [comment]
去掉打印信息把，我调试用的，忘记删除了。
