### ISSUE TITLE
发行的TOKEN的symbol支持大写英文字母加数字的格式

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#209]
需求来自供应链金融开发团队， 他们需要根据应收账款的名称（包含数字，时间等）来发行token。 希望在token名称上带上数字。
@vipwzw   帮忙看下，是只在平行链上实现这个功能，还是平行链主链都支持。

**Comment by vipwzw** [comment]
主链和平行链都支持，需要分叉。

**Comment by vipwzw** [comment]
支持大写字母+ 数字 @linj-disanbo

**Comment by linj-disanbo** [comment]
好的

**Comment by vipwzw** [comment]
@linj-disanbo  新增一个字段，属性字段，代表这个币的特性。比如是稳定币，还是普通token，或者白条之类的，先做保留字段。

**Comment by linj-disanbo** [comment]
我重新开一个issue ，做增加属性字段https://github.com/33cn/plugin/issues/220
