### ISSUE TITLE
挖矿时，无法自动close

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#23]
开启自动挖矿的钱包挖矿时，不会自动close
地址：1K7Fko7e21F2qXdYriVLheJue5ZW5KerZL

**Comment by jixingwei** [comment]
可能之前的本地数据没有清除，虽然新版本不会再次产生这种情况，但是老的数据还在，一种办法是在代码里加一个规避，wallet从ticket执行器获取到票的时候，再进行一次判断过滤，把状态是3的过滤掉，不再触发这个票的关闭（List是从localDB找的，返回的数据在stateDB，所以可以再次判断状态）

**Comment by jixingwei** [comment]
@vipwzw 看看这样做行不行

**Comment by vipwzw** [comment]
重新新升级localdb 可以解决这个问题吗？如果可以，把localdb的version 提高就可以了。

**Comment by jixingwei** [comment]
应该可以，前面的错误交易还是执行不过，但是等到后面这个节点再去发关闭交易的时候，不会带上这个已经关闭的票了

**Comment by vipwzw** [comment]
重新升级localdb 已经可以了。
