### ISSUE TITLE
[EVM合约] 数据写入区块后，调用查询接口没有返回。

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#245]
数据写入区块链后，调用查询接口返回值为空。

**Comment by andyYuanFZM** [comment]
合约代码如下：

pragma solidity ^0.4.18;

contract RuncoMedical {

    struct MdInfo {
        address creator;    //信息录入者地址
        string name;		//名称
        uint price;		    //价格
        string codeno;		//编码
        string batchno;		//批号
        string desc;        //其他扩展信息
    }
    uint mds_number = 0;    //药品数量
    mapping (uint  => MdInfo) medicallst; // key 为商品唯一编号

    function utilCompareInternal(string memory a, string memory b) internal pure returns (bool) {
        if (bytes(a).length != bytes(b).length) {
            return false;
        }
        for (uint i = 0; i < bytes(a).length; i ++) {
            if(bytes(a)[i] != bytes(b)[i]) {
                return false;
            }
        }
        return true;
    }

    // 增加商品信息
    function addMdInfo(address _creator, string memory _name, uint _price, string memory _codeno, string memory _batchno, string memory _desc ) public {
        MdInfo memory item = MdInfo(_creator, _name, _price, _codeno, _batchno, _desc);
        medicallst[mds_number] = item;
        mds_number = mds_number + 1;
    }
 
    // 修改商品
    function updateMdInfoByCodeNo(string memory _codeno, string memory _name, string memory _batchno, uint _price) public {
        uint _index = getMdIndexByCodeNo(_codeno);
        MdInfo memory item = medicallst[_index];
        item.name = _name;
        item.batchno = _batchno;
        item.price = _price;
        medicallst[_index] = item;
    }

    // 获得商品  

    function getMdInfoByIndex(uint _index) public view returns(address, string memory, uint, string memory, string memory, string memory) {
        MdInfo memory item = medicallst[_index];
        return (item.creator, item.name, item.price, item.codeno, item.batchno, item.desc);
    }

    function getMdIndexByCodeNo(string memory _codeno) public view returns(uint) {
        uint _index;
        for (uint8 index = 0; index < mds_number; index++) {
            MdInfo memory item = medicallst[index];
            bool isEq = utilCompareInternal(_codeno, item.codeno);
            if(isEq)
                _index = index;
        }
        return _index;
    }

    function getMdInfoByCodeNo(string memory _codeno) public view returns(address, string memory, uint, string memory, string memory, string memory) {
        uint _index = getMdIndexByCodeNo(_codeno);
        return getMdInfoByIndex(_index);
    }

    function getMdNumber() public view returns(uint) {
        return mds_number;
    }
}

**Comment by andyYuanFZM** [comment]
@jixingwei  帮忙看下这个问题， 开发者反馈创建EVM合约成功，写入数据成功，但是调用查询接口没有数据返回。

**Comment by jixingwei** [comment]
好的，我分析一下问题

**Comment by vipwzw** [comment]
遇到问题，可以找何政军求助

**Comment by chengwei1104** [comment]
@zhengjunhe 请问该问题处理结果咋么样了？

**Comment by jixingwei** [comment]
@chengwei1104 
我本地环境测试了一下这个合约的创建，更新数据调用，查询数据调用，可以工作；
请更详细地描述一下：
1. 是在什么环境下测试的，如果是BITYUAN主链，请提供创建EVM合约，调用合约相关交易HASH；是如何判断创建和调用都是没有问题的。我听袁子说可能是自己搭建的链，那么这里需要注意,EVM合约的使能是有一定高度的；
2. 是使用命令行，还是脚本测试的，是否使用ABI，如果是脚本，最好能把脚本发给我们直接测试一下

**Comment by zhengjunhe** [comment]
@chengwei1104 请按照@jixingwei的建议进行问题的确认吧，如果过程中，需要帮忙，@jixingwei，直接找我好了。

**Comment by chengwei1104** [comment]
@jixingwei 使用abi java-sdk存储和查询，存储后有信息返回，查询jsonData为空，存储和查询均无错误，只是查不到数据。我使用的是自己搭建的链，本地节点。
EVM合约的使能是有一定高度的；==》》》这个设定值能否告知下，应该怎么设置

**Comment by andyYuanFZM** [comment]
将合约版本更新成 pragma solidity ^0.5.2 ， 可以解决这个问题。
