### ISSUE TITLE
oracle/rpc 单元测试 有时候会超时

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#246]
**Describe the bug**
在单元测试时， 输入 make test , 预期通过测试，结果 oracle/rpc 超时
EROR[01-18|17:34:58] ProcQueryTxMsg                           module=blockchain err="tx not exist"
EROR[01-18|17:34:58] QueryTx                                  module=client Error="tx not exist"
EROR[01-18|17:34:58] ProcQueryTxMsg                           module=blockchain err="tx not exist"
EROR[01-18|17:34:58] QueryTx                                  module=client Error="tx not exist"
EROR[01-18|17:34:58] ProcQueryTxMsg                           module=blockchain err="tx not exist"
EROR[01-18|17:34:58] QueryTx                                  module=client Error="tx not exist"
EROR[01-18|17:34:58] ProcQueryTxMsg                           module=blockchain err="tx not exist"
EROR[01-18|17:34:58] QueryTx                                  module=client Error="tx not exist"
EROR[01-18|17:34:59] ProcQueryTxMsg                           module=blockchain err="tx not exist"
EROR[01-18|17:34:59] QueryTx                                  module=client Error="tx not exist"
EROR[01-18|17:34:59] ProcQueryTxMsg                           module=blockchain err="tx not exist"
EROR[01-18|17:34:59] QueryTx                                  module=client Error="tx not exist"
panic: ErrTimeout

goroutine 58 [running]:
github.com/33cn/plugin/vendor/github.com/33cn/chain33/queue.(*client).Wait(0xc420774840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/linj/work/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/queue/client.go:132 +0x29d
github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/consensus.(*BaseClient).RequestTx(0xc420162a80, 0x2710, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/linj/work/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/consensus/base.go:277 +0x2f6
github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/consensus/solo.(*Client).CreateBlock(0xc42078a760)
	/home/linj/work/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/consensus/solo/solo.go:107 +0x1d1
created by github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/consensus.(*BaseClient).SetQueueClient
	/home/linj/work/src/github.com/33cn/plugin/vendor/github.com/33cn/chain33/system/consensus/base.go:118 +0x114
FAIL	github.com/33cn/plugin/plugin/dapp/oracle/rpc	305.908s

**Comment by Hugo-Huang** [comment]
在本机测试多次未能重现，继续观察。

**Comment by andyYuanFZM** [comment]
目前这个问题没有重现过，先关闭此issue。
