### ISSUE TITLE
Goroutine leak in parachain

### ISSUE THREAD

**Issue by caopingcp** [33cn/plugin#252]
**Describe the bug**
Goroutine leak occurs in parachain

**To Reproduce**
1. Run chain33 parachain
2. Check the goroutine number
3. See error

**Expected behavior**
Many goroutines in parachain process.

**Screenshots**
![image](https://user-images.githubusercontent.com/22811866/51457109-10248800-1d8b-11e9-95ab-33d84608ae3e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS

**Comment by jixingwei** [comment]
@vipwzw 每次执行TX，会新建一个paraChainApi，这里建立了grpc连接，如果在setEnv的地方增加一个defer cleanEnv这样的处理合适吗？或者明天有时间能讨论一下

**Comment by vipwzw** [comment]
我看一下怎么修复
