### ISSUE TITLE
paracross合约无法取回主链转入平行链的token

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#259]
**Describe the bug**
paracross合约无法取回主链转入平行链的token，需要增加对主链token取回的支持

**Screenshots**
![image](https://user-images.githubusercontent.com/44956625/51576219-5cd5a380-1ef0-11e9-8280-be126f680aca.png)

![image](https://user-images.githubusercontent.com/44956625/51576232-67903880-1ef0-11e9-8e7a-4d769cc76953.png)

@linj-disanbo

**Comment by zhengjunhe** [comment]
https://github.com/33cn/plugin/pull/274
