### ISSUE TITLE
unfreeze 终止解冻合约后，在list中查询得到的终止状态没有改变

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#279]
**Describe the bug**
unfreeze 终止解冻合约后，在list中查询得到的终止状态没有改变，而实际状态已经终止，根据id通过show查询的状态也已经改变
![image](https://user-images.githubusercontent.com/44956625/51797870-7e62c200-2245-11e9-81fe-ea87db9bcd0f.png)

![image](https://user-images.githubusercontent.com/44956625/51797864-72770000-2245-11e9-8846-f3e2ca0a1b40.png)

**Comment by vipwzw** [comment]
@linj-disanbo
