### ISSUE TITLE
trade合约调用sell_market时，输入错误的buy_id，报错信息有误

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#288]
**Describe the bug**
trade合约调用sell_market时，输入的buy_id为某个存在的sell_id,交易执行后返回的错误信息为ErrExecNameNotAllow

![image](https://user-images.githubusercontent.com/44956625/51824013-1b902a00-231c-11e9-9337-51f2d43e6a08.png)

**Comment by xies1031** [comment]
@linj-disanbo

**Comment by harrylee2015** [comment]
这个问题应该和这个issue 类似，匹配错了
https://github.com/33cn/plugin/issues/226
