### ISSUE TITLE
retrieve需要支持所有token

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#289]
目前的retrieve功能只支持bty，其余token未支持。下个版本中需要增加对所有token的支持。

**Comment by andyYuanFZM** [comment]
@jixingwei  帮忙处理下这个需求。

**Comment by jixingwei** [comment]
@andyYuanFZM @vipwzw 
实现思路如下：
备份，准备过程不变，在执行的时候，除了将coins进行ExecTransfer以外，对所有默认地址在retrieve合约下的token(所有symbol)进行ExecTransfer.
该方案分析/实施过程遇到的问题目前有：（问题2，3请参照分支代码，https://github.com/33cn/plugin/pull/334）
1. 需要token合约以及适当的rpc接口，提供查询在某一个合约下，所有symbol的token，token合约目前有这样的接口，但是存在问题，已经提issue333，另外这样的接口应该提供到api，以供retrieve或其他合约方便操作；
2. 在执行token的ExecTransfer时，需要使用token的accountdb，这个时候NewAccountDB会覆盖statedb里之前的accountDB（coinsdb）
3. 在执行token的ExecTransfer时，产生的KV是否能通过后续KV的检查

**Comment by linj-disanbo** [comment]
1. token 里有接口 GetAccountTokenAssets 可以获得所有的symbol， 但不支持 retrieve 参数。 我会在明天前fix 这个问题。 
2 & 3 需要调试下， 应该是代码bug

**Comment by jixingwei** [comment]
@linj-disanbo 我调试了一下代码，2&3确实是因为bug引起的，我自己把数据覆盖了。1这个问题，我在本地合并了你的修改，可以生效，但是这里有一个问题需要确认，就是这个数据是从localdb里获取的，如果是token自身finish，transfer以后，没有问题；如果是在其他合约，进行了转移，比如说，A 在合约retrieve里转给了B，那么这个时候用token_assets是不是不能查B的数据了

**Comment by linj-disanbo** [comment]
> @linj-disanbo 我调试了一下代码，2&3确实是因为bug引起的，我自己把数据覆盖了。1这个问题，我在本地合并了你的修改，可以生效，但是这里有一个问题需要确认，就是这个数据是从localdb里获取的，如果是token自身finish，transfer以后，没有问题；如果是在其他合约，进行了转移，比如说，A 在合约retrieve里转给了B，那么这个时候用token_assets是不是不能查B的数据了

1. 是从 localdb 得到数据
2. 只有在token 合约处理过，才有数据。 你举的例子 B 是没有数据的。 retrieve 没有权限写 token 的记录， 不然在A 转给B 时， 可以在local exec 把数据不伤。 原来 trade 是这样做的。 后来不能跨合约写， 这部分代码去掉了。

**Comment by vipwzw** [comment]
@linj-disanbo  有空处理一下这个问题

**Comment by linj-disanbo** [comment]
> @linj-disanbo 有空处理一下这个问题

#600 处理后处理

**Comment by linj-disanbo** [comment]
现在有两种做法
 1. 一种是访问 token 合约的 local db 部分， 得到发起者有哪些资产。 
 1. 一种由backup 地址在执行时， 指定一组资产， 转移指定资产。 可多次转移。 

我倾向第二种做法
 1. 以后可能不止有 coins  token 合约有资产
 1. 可以在外部（app）获得发起帐号的资产列表， 比如现在token有对应的接口 GetAccountTokenAssets。 

@vipwzw

**Comment by linj-disanbo** [comment]
采用由外部指定资产
