### ISSUE TITLE
EVM合约需要支持绑定ABI

### ISSUE THREAD

**Issue by litian33** [33cn/plugin#29]
增加以下特性：
- EVM合约支持绑定ABI；
- EVM合约支持ABI格式的rpc调用；
- EVM合约支持ABI格式的命令行调用；

**Comment by zhengjunhe** [comment]
这个目前有设计和分析了吗？
EVM合约支持ABI格式的rpc调用；
EVM合约支持ABI格式的命令行调用；
上述2项分别具体什么意思？因为在我看来，命令行调用最后也是需要rpc调用来驱动EVM的执行的啊

**Comment by vipwzw** [comment]
@litian33  可以参考这个代码：https://github.com/ethereum/go-ethereum/tree/master/accounts/abi

**Comment by litian33** [comment]
# EVM支持ABI绑定和调用

## 1 背景
> 目前Chain33中已经支持了EVM合约，可以通过命令行或RPC接口将EVM合约部署到Chain33中，并支持对合约的调用；

### 1.1 存在的问题
首次实现EVM合约支持方案时，考虑工作量的问题，没有实现对ABI的支持，而是借助了Remix IDE的能力，对合约进行部署和调用；

需要使用Remix模拟部署，然后使用生成的二进制代码在Chain33中部署EVM合约； 也需要使用Remix模拟调用，生成调用方法的二进制信息，然后在Chain33中进行合约的调用；

在使用者进行使用的时候不太方便，也不利于外部程序的自动化处理；

### 1.2 改进方案
EVM合约支持绑定ABI接口文件，然后使用ABI中的方法签名进行调用，摆脱对Remix IDE的依赖，方便自动化包装；

## 2 设计理念
> EVM合约实现时参考了以太坊的实现，交易Action只定义了一种结构，然后根据目标对象地址判断是部署合约还是调用合约；

为了保证EVM合约的兼容性，无法通过新增Action结构的方式提供对ABI的支持，不过可以通过其它方式实现；我们可以在目前合约调用的动作上进行改进：

在合约调用逻辑中，判断输入数据的前4个字节，根据取值执行相应的动作：

- 为0x00000000时：
  
  代表本次动作为绑定ABI操作，后面的数据将被视为ABI数据进行解析，然后写入到区块数据库；
- 为0xffffffff时：
  
  代表本次动作为ABI格式的合约调用，后面的数据将按照ABI的数据结构进行解析，然后调用对应的合约方法；

- 为其它值时：
  
  代表本次动作为原有的合约调用，走已有逻辑；


## 3 实现方案

### 3.1 ABI绑定和ABI调用
在原有EVM创建交易的RPC接口中，增加BindABI和CallABI两种操作类型，分别支持的参数如下：

- **BindABI:**
    - ABI数据（十六进制）
    - 要绑定的EVM合约地址

- **CallABI:**
    - EVM合约地址
    - 合约方法的ABI签名数据（十六进制）
    - 转账金额

在这两个动作中，根据上一章中的设计思路，对合约的输入数据进行处理，生成对应的前缀信息，满足合约执行时的处理逻辑；

### 3.2 命令行支持
新增 evm abi bind 和evm abi call 两个子命令，分别调用绑定和调用ABI的RPC接口；

## 4 其它约束
1. 只有合约的创建者有权限发起绑定操作；
1. 同一个合约的ABI可以多次绑定，交易处理时会使用最新绑定的数据；

具体abi数据的解析支持参考以太坊实现逻辑：https://github.com/ethereum/go-ethereum/tree/master/accounts/abi

**Comment by litian33** [comment]
本功能在这个分支中进行开发 https://github.com/litian33/plugin/tree/evm_abi

**Comment by vipwzw** [comment]
@litian33  以太坊上好像没有bindabi的动作，abi是不是包含在编译的内容里面了？

**Comment by vipwzw** [comment]
https://github.com/ethereum/go-ethereum/blob/master/cmd/abigen/main.go

**Comment by vipwzw** [comment]
```
        web3.eth.contract(abi).new({data: code}, function (err, contract) {
            if(err) {
                console.error(err);
                return;
            // callback fires twice, we only want the second call when the contract is deployed
            } else if(contract.address){
                myContract = contract;
                console.log('address: ' + myContract.address);
                document.getElementById('status').innerText = 'Mined!';
                document.getElementById('call').style.visibility = 'visible';
            }
        });
```
看上去abi 和 code 都会上传

**Comment by litian33** [comment]
@vipwzw  前两天和 @zhengjunhe  沟通过，这个实现方式我做了变更，现在也是在创建合约的同时绑定ABI，并且将ABI的调用方式和旧的合约调用方式做了统一；

这个实现之后，再增加另外一个特性： #66 EVM合约的只读调用数据不上链
