### ISSUE TITLE
tendermint共识 单元测试时超时。

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#318]
执行单元测试时，有时会出现 ErrQueueTime的错误。

**Comment by andyYuanFZM** [comment]
@Hugo-Huang 帮忙看下这个问题

**Comment by 33cn** [comment]
发一下错误信息的链接

**Comment by andyYuanFZM** [comment]
错误信息： https://travis-ci.org/33cn/plugin/jobs/493578601
