### ISSUE TITLE
token token_assets查询在其他合约的数据无显示

### ISSUE THREAD

**Issue by jixingwei** [33cn/plugin#333]
**Describe the bug**
token send_exec到其他合约，再查询余额，用balance可以显示,asset不能正常显示

$ ./cli token token_balance -s ABC -e retrieve -a 1APTdLW4pmJpJ4rjEv5bUsnwnneALeS7oK
[
    {
        "Token": "ABC",
        "balance": "100.0000",
        "frozen": "0.0000",
        "addr": "1APTdLW4pmJpJ4rjEv5bUsnwnneALeS7oK"
    }
]

HR@DESKTOP-57CK99B MINGW64 /c/Go/src/github.com/33cn/plugin/cli (retrieve_support_token)
$ ./cli token token_assets -a 1APTdLW4pmJpJ4rjEv5bUsnwnneALeS7oK -e retrieve
ErrNotFound

**To Reproduce**
1.产生token
2.将token打入其他合约

**Expected behavior**
能够正常显示

**Comment by xies1031** [comment]
trade合约下的资产是能显示的。
具体的情况 @linj-disanbo

**Comment by xies1031** [comment]
https://github.com/33cn/chain33/issues/268#issue-397700430

**Comment by linj-disanbo** [comment]
不能显示其他合约的问题已经解决
https://github.com/33cn/plugin/pull/13

**Comment by andyYuanFZM** [comment]
问题已经解决，关闭此issue
