### ISSUE TITLE
norm执行器需要设置为收费模式，不然存在安全隐患

### ISSUE THREAD

**Issue by harrylee2015** [33cn/plugin#338]
**Describe the bug**
用norm进行写数据的测试时，发现执行器是不收手续费的，这样可能存在被人恶意利用，进行流量攻击，恶意拥堵chain33区块链网络，需要检查一下比特元现网中是否存在这样的问题
https://github.com/33cn/plugin/blob/master/plugin/dapp/norm/executor/norm.go#L40

**Comment by xies1031** [comment]
主链上没有norm这个执行器

**Comment by harrylee2015** [comment]
嗯，看了，是没有

**Comment by harrylee2015** [comment]
#338
