### ISSUE TITLE
平行链区块tx连续执行出错时候，如果是分叉区块，考虑跳过分叉区块执行

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#340]
如果平行链tx连续执行出错n次，往更高查找是否有delete type，也就是分叉恢复区块，如果有，跳过此区块和下一个delete type的区块来继续执行，要至少考虑3个区块连续delete场景，其中任何一个区块执行出错场景

**Comment by mdj33** [comment]
经沟通，目前平行链执行器和共识共用一个grpc cli 出错的概率应该很低了，即便出错也应该能比较快的恢复，先观察一段时间再看

**Comment by vipwzw** [comment]
需要继续观察，这个问题是否需要修复待定。
