### ISSUE TITLE
类似eos的dpos共识

### ISSUE THREAD

**Issue by vipwzw** [33cn/plugin#341]
简单的dpos共识，实现类似eos，云象区块链的共识算法。

**Comment by andyYuanFZM** [comment]
使用dpos+bft的方式实现些共识插件，方案初稿如下：
https://github.com/andyYuanFZM/projectFile/blob/master/DPos%E5%AE%9E%E7%8E%B0%E6%96%B9%E6%A1%88.md

**Comment by vipwzw** [comment]
先实现 dpos， 不考虑 bft。

**Comment by vipwzw** [comment]
越简单的东西越不容易出错，先实现一个最简单版本的 dpos 。 dpos + bft 作为另外一个共识来实现，这样，部分场景下，可能dpos 就够不需要 bft。

**Comment by zzh33cn** [comment]
chain33 dpos的算法介绍，参见如下文档的第七节:

https://gitlab.33.cn/richardzhang/share/blob/master/dpos%E5%85%B1%E8%AF%86/DPOS%E5%85%B1%E8%AF%86%E7%AE%97%E6%B3%95%E4%BB%8B%E7%BB%8D.md

**Comment by vipwzw** [comment]
代码差不多了，就更新上来吧

**Comment by vipwzw** [comment]
这个更新放到 6.4 版本把
