### ISSUE TITLE
由于接口调整，GetLotteryBuyRoundInfo接口不可用。

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#352]
localdb.go中的PrefixCount方法改成不支持根据prefix全表查询， lottery游戏中的GetLotteryBuyRoundInfo接口调用此方法出错。

**Comment by andyYuanFZM** [comment]
嗯，已经在调整了。

**Comment by vipwzw** [comment]
如果真的需要count 需要在设计的时候就考虑这个count
