### ISSUE TITLE
token增发及燃烧的数值问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#361]
目前测试中发现，token一次增发及燃烧的上限是10亿，若目标数值超过10亿则需要经过多次操作。是否需要去掉这个限制？
![image](https://user-images.githubusercontent.com/44956625/54415462-4e10ad80-4737-11e9-8040-11ea616972da.png)

**Comment by linj-disanbo** [comment]
10亿基本上够，先不该把
