### ISSUE TITLE
【token合约】执行revoke后，无法再次precreate

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#364]
再次precreate时提示：ErrOwnerHaveTokenPrecreateYet

**Comment by andyYuanFZM** [comment]
@vipwzw @linj-disanbo 
针对这个bug，想到一个问题。
以guodun发币操作为例 ：
bug修改前：
1. precreate--> revoke-->再次precreate -->finish.    由于bug的存在，这一发币流程会失败。
2. 切换owner地址，对同一个symbol再次precreate-->finish.    发币成功。

bug修改后，如果国盾升级版本，并且从0开始同步数据
precreate--> revoke-->再次precreate -->finish.   这一步发币就可以成功了。 而第2步由于symbol重复会失败。

那么后续跟这个symbol相关的交易会不会都有问题？  是不是需要针对guodun做个特殊处理，这个修改永远不生效？

**Comment by linj-disanbo** [comment]
和执行结果有关的bug修改， 需要分叉。 配置一个高度， 指定这个修复在什么高度生效。
在国盾升级版本的时候， 配置这个分叉就可以， 保证执行结果和原来的一样

**Comment by linj-disanbo** [comment]
> @vipwzw @linj-disanbo
> 针对这个bug，想到一个问题。
> 以guodun发币操作为例 ：
> bug修改前：
> 
> 1. precreate--> revoke-->再次precreate -->finish.    由于bug的存在，这一发币流程会失败。
> 2. 切换owner地址，对同一个symbol再次precreate-->finish.    发币成功。
> 
> bug修改后，如果国盾升级版本，并且从0开始同步数据
> precreate--> revoke-->再次precreate -->finish. 这一步发币就可以成功了。 而第2步由于symbol重复会失败。
> 
> 那么后续跟这个symbol相关的交易会不会都有问题？ 是不是需要针对guodun做个特殊处理，这个修改永远不生效？

和执行结果有关的bug修改， 需要分叉。 配置一个高度， 指定这个修复在什么高度生效。
在国盾升级版本的时候， 配置这个分叉就可以， 保证执行结果和原来的一样
