### ISSUE TITLE
token增发及燃烧，传递的asset为null

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#366]
token增发及燃烧，传递的asset为null，导致前端浏览器取到token价值为空
![image](https://user-images.githubusercontent.com/44956625/54501398-0751cc00-4960-11e9-862f-5e17ce4d4727.png)

@linj-disanbo

**Comment by linj-disanbo** [comment]
现在只有转账的那几个操作支持

**Comment by xies1031** [comment]
让前端针对这类操作取价值0
