### ISSUE TITLE
最新plugin代码，开启quickindex后，内存飙升

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#369]
开启quickindex后，内存飙升
![image](https://user-images.githubusercontent.com/44956625/54512717-1486af00-4990-11e9-96d6-f00b31ff183b.png)

**Comment by icehawk-hyb** [comment]
看日志打印是在quickIndex改造数据库

**Comment by xies1031** [comment]
修改成2000处理一次并reset后正常
![image](https://user-images.githubusercontent.com/44956625/54587490-2da86200-4a5b-11e9-9a4b-aebaf498019a.png)

**Comment by xies1031** [comment]
更新后4c8gssd quickindex耗时50min，内存稳定在500
