### ISSUE TITLE
使用默认配置同步测试链代码，同步完成后内存没有释放

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#379]
使用默认配置同步测试链代码，同步完成后内存没有释放
![image](https://user-images.githubusercontent.com/44956625/55123603-3f19fa00-513e-11e9-8c71-5fa6d34045d2.png)

**Comment by lyh169** [comment]
> 使用默认配置同步测试链代码，同步完成后内存没有释放
> ![image](https://user-images.githubusercontent.com/44956625/55123603-3f19fa00-513e-11e9-8c71-5fa6d34045d2.png)

缓存中内存中的树节点不会释放，但是可以看到，内存已经有峰值5602M释放到大概2047M

**Comment by lyh169** [comment]
> > ![image](https://github.com/lyh169/photo/blob/master/not_save_ticket_close.jpg)

这个是我将ticket close 不缓存的时候 测试的数据，应该来说高度更加高一点，这个是在blcokchain不优化的情况下
