### ISSUE TITLE
部署本地单节点时仍然连接其他节点

### ISSUE THREAD

**Issue by hnshhslsh** [33cn/plugin#381]
**Describe the bug**
用 master 分支的代码，按照官方文档部署本地单节点时，仍然连接其他节点，并且无法同步。

**To Reproduce**
1. 使用 [https://github.com/33cn/plugin.git](https://github.com/33cn/plugin.git) 的 master 分支代码进行 make
2. 使用 [https://chain.33.cn/document/120](https://chain.33.cn/document/120) 的说明配置`chain33.toml`文件
3. 执行`./chain33 -f chain33.toml >> log.out 2>&1 &`运行节点程序
4. 执行`./chain33-cli net is_sync`发现始终为 `false`
5.  执行`./chain33-cli net peer_info`发现节点列表里有其它 IP

**Expected behavior**
`./chain33-cli net is_sync`返回 `true`，节点列表无其它 IP

**Screenshots**
<img width="1007" alt="WX20190401-173430@2x" src="https://user-images.githubusercontent.com/9738445/55318102-84268f00-54a4-11e9-8fc4-1e05ab83ce9b.png">

**Environment:**
 - OS: ubuntu-16.04.6-server-i386

**Comment by andyYuanFZM** [comment]
看上去像是连到测试网去了，我看下。

**Comment by andyYuanFZM** [comment]
@hnshhslsh  P2P模块的代码有更新，现在改成：p2p网络里内置了默认种子，一个测试网络的，一个是正式网络的。这两个必选其一。 
增加p2p的版本号来隔离网络，配置文档已经更新。【P2P】模块下增加以下配置项， 值可以自己定义。
# p2p版本号，不同的测试网络选用不同的version
version=200
verMix=200
verMax=200

**Comment by vipwzw** [comment]
错误删除了部分代码，正在修复
