### ISSUE TITLE
本地数据库信息展开

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#402]
**Is your feature request related to a problem? Please describe.**
随着应用的增多， 后续对本地数据库的要记录的数据也将越来越多。 

目前有记录的需要如下：
 
1.  资产排名， 取top N
1.  一个地址拥有的所有的token 列表
1. 和token相关的交易的列表
1. 挖矿是否正常数据
1. 交易订单相关的列表
1. 等等

这些数据有以下特点
 1. 数据是可选的。  他们不是必要的状态数据， 可能在状态数据库不容易获得， 可能需要在本地执行中添加代码并将数据保存在本地（而无关的节点也会因此对存储的需要变大）， 只在某些特点app 中用到。
 1. 顺着需求变化而变化
 1. 顺着需求的增多而增多

**Describe the solution you'd like**
 
 在节点外部署依赖于节点的数据库， 用额外的程序同步节点信息， 并将数据展开，写到数据库。 这部分可以相对独立
 1. 数据可以分应用展开到不同的数据库， 也可以一起
 1. 可以不需要和节点一起更新， 对应需要变化， 可以额外部署，也可以添加到老的数据库中
 

**Describe alternatives you've considered**

**Additional context**

**Comment by vipwzw** [comment]
代码已经更新到内网，这部分代码没有开源。
