### ISSUE TITLE
【EVM】更新plugin代码后跑测试链，stateDB升级过程中报错

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#404]
拉取最新plugin代码，因stateDB版本变更，自动升级stateDB。升级至692551报错，该区块中有evm交易。
![image](https://user-images.githubusercontent.com/44956625/56339868-89911280-61e2-11e9-9ace-7ccffaef4bc3.png)

**Comment by andyYuanFZM** [comment]
@lynAzrael  李麟跟踪下这个问题。

**Comment by lynAzrael** [comment]
好的

**Comment by vipwzw** [comment]
@lyh169 你也看一下

**Comment by lyh169** [comment]
> @lyh169 你也看一下

ok

**Comment by lyh169** [comment]
![QQ截图20190423171707](https://user-images.githubusercontent.com/44960676/56569492-a7e47d00-65eb-11e9-905a-56403f228156.png)
这个区块里面也就是update store 时候evm交易生成的kv对数目不一样，
![微信图片_20190423171957](https://user-images.githubusercontent.com/44960676/56569723-1f1a1100-65ec-11e9-9466-6d7e98f73174.png)
打印出来GetState函数获取的状态不一样；，外部执行函数我统一用的是同一个，且该区块交易树hash是一样。

**Comment by xies1031** [comment]
已修复
