### ISSUE TITLE
交易组交易在进入mempool时未进行去重校验

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#406]
流程步骤：
构造交易A、交易B、交易C为交易组，签名并发送，打包并在区块链上执行；
构造交易D、交易E、交易C为交易组，此时的交易C为重复交易，同样签名并发送后，返回交易哈希并进入内存池，在执行时被去重清除。

预期：重复交易应在进入mempool时被mempool校验去重，避免进入mempool形成攻击。

**Comment by xies1031** [comment]
单笔交易在进入mempool时会被去重校验
![image](https://user-images.githubusercontent.com/44956625/56419989-d6521780-62ce-11e9-862d-d0b1e5911869.png)

**Comment by vipwzw** [comment]
先不要公开这个issues，这个会形成攻击。
