### ISSUE TITLE
wasm合约调用GetRandNum接口时偶现错误

### ISSUE THREAD

**Issue by yann-sjtu** [33cn/plugin#417]
![image](https://user-images.githubusercontent.com/29310615/56938182-13ba6e80-6b33-11e9-8c5f-a62be4fd9001.png)

**Comment by zhengjunhe** [comment]
应该不是wasm合约本身的问题，可能跟GRPC有关，搭一个测试环境，反复调用，尽快复现问题

**Comment by vipwzw** [comment]
这个问题解决了吗？

**Comment by yann-sjtu** [comment]
> 这个问题解决了吗？

已经解决了，一方面让grpc保持长连接，另一方面在wasm里处理grpc的错误，grpc出问题时retry

**Comment by yann-sjtu** [comment]
> 这个问题解决了吗？

这个接口跟平行链往主链发交易用的是同一个grpc，让grpc保持长连接林敬之前应该已经合过了，wasm没有拉新的chain33代码导致的。后面wasm拉了新的代码然后也wasm里加了grpc的错误处理逻辑了
