### ISSUE TITLE
[平行链] 无法从release6.1.0版本平滑升级到目前最新版本，出现panic

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#418]
step:
1. release6.1版本同步一条平行链。
2. 编译最新的plugin版本，替换之前的主程序。
3. 运行最新的版本。

现象：
日志中，先开始执行ExecBlockUpgrade，然后出现以下error log:
EROR[04-30|08:31:20] GetSeqByHashOnMainChain                  module=para Error="rpc error: code = Unknown desc = ErrInvalidParam"
接着出现panic，程序退出：

EROR[04-30|08:31:20] switchHashMatchedBlock depth overflow    module=para last info:mainHeight=0 mainHash= search startHeight=37843 curHeight=37744 search depth=100
panic: search HashMatchedBlock overflow, re-setting search depth and restart to try

goroutine 276252 [running]:
github.com/33cn/plugin/plugin/consensus/para.(*client).switchHashMatchedBlock(0xc012a28780, 0x1e4b8a, 0xc0019e2a90, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/qkl2/go/mypath/src/github.com/33cn/plugin/plugin/consensus/para/para.go:505 +0x1298
github.com/33cn/plugin/plugin/consensus/para.(*client).CreateBlock(0xc012a28780)
        /home/qkl2/go/mypath/src/github.com/33cn/plugin/plugin/consensus/para/para.go:586 +0x1db
created by github.com/33cn/plugin/plugin/consensus/para.(*client).SetQueueClient
        /home/qkl2/go/mypath/src/github.com/33cn/plugin/plugin/consensus/para/para.go:186 +0x141

**Comment by mdj33** [comment]
由于6.1版本平行链block 结构不支持mainHash和mainHeight新的参数，在新的版本里面赋值并使用了这两个参数，切换新版本需要删除老的数据库重新同步

**Comment by vipwzw** [comment]
需要配置fork 高度吧

**Comment by mdj33** [comment]
有些能加fork的也考虑了，主要是这个block结构的改动，需要重跑block数据库，不然这个高度回溯时候也不确定，跟主链sequence类似
	if types.IsPara() {
		blockbody.MainHash = blockdetail.Block.MainHash
		blockbody.MainHeight = blockdetail.Block.MainHeight
	}
但是这个改动不会影响statehash，如果有statehash的变化还是要确认下什么原因的
