### ISSUE TITLE
travis deploy testcase 不稳定

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#47]
travis 云端跑testcase 不稳定，jq解析不对，命令卡住，docker 启动失败等问题
建议：
1， travis 工程 setting里面可以设置变量DAPP，如果DAPP设置了，travis只跑DAPP的testcase，否则不跑
2，all plugin的case当前放到jenkins里面跑，独立服务器，更加稳定

**Comment by vipwzw** [comment]
jenkins 体验差不多了，就可以转过去。
