### ISSUE TITLE
执行器retrieve,lottery,ticket本地数据执行逻辑错误

### ISSUE THREAD

**Issue by jixingwei** [33cn/plugin#49]
1. retrieve执行器在处理回滚数据时，出现代码循环调用
2. lottery，ticket执行器本地处理回滚数据缺少有效代码

**Comment by vipwzw** [comment]
#25 #23 #15 看看是否都是相同的问题

**Comment by jixingwei** [comment]
#23 #25看现象应该是一样的，#15还需要再分析一下
