### ISSUE TITLE
双色球合约

### ISSUE THREAD

**Issue by caopingcp** [33cn/plugin#53]
需求内容：
-  管理员发布双色球竞猜到区块链合约上

-  DAPP用户可参与投注
如果已停止投注（到时间或者区块高度），则DAPP上不能再进行投注，如果尝试投注，将失败

- 过了投注时间后，管理员向区块链合约揭晓结果，并触发合约结算
按照双色球的通用规则进行结算，奖池不断累加

- 用户可查询自己的投注历史记录

**Comment by vipwzw** [comment]
@caopingcp @andyYuanFZM  可以把随机数部分提炼出来

**Comment by andyYuanFZM** [comment]
魏吉星正在搞，后面打算搞成一个插件。

**Comment by jixingwei** [comment]
正在调试，想法是做一个与dapp并行的插件，这个插件有base，具体实现分ticket/dpos，当前先实现dpos
