### ISSUE TITLE
针对升级时候出现小概率 的Get version by hash failed问题做个跟踪

### ISSUE THREAD

**Issue by lyh169** [33cn/plugin#533]
后续，写出错都painc掉
![微信图片_20190621195820](https://user-images.githubusercontent.com/44960676/59921017-fa60df00-945e-11e9-92b5-f539ddfbff31.png)

**Comment by vipwzw** [comment]
@lyh169  哪个pr 解决了这个问题需要引用一下

**Comment by lyh169** [comment]
https://github.com/33cn/plugin/pull/538
