### ISSUE TITLE
mempoolsize的统计一直没有删除

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#539]
![image](https://user-images.githubusercontent.com/44956625/60070251-8bc69e80-9748-11e9-8f78-5fc043ded984.png)
mempoolsize的数据一直在80多，没有删除，实际链上没有这么多交易，查询mempool list为空
![image](https://user-images.githubusercontent.com/44956625/60070293-b9134c80-9748-11e9-966f-6653baf8db49.png)

**Comment by xies1031** [comment]
@CCCCCDH @icehawk-hyb

**Comment by xies1031** [comment]
![image](https://user-images.githubusercontent.com/44956625/60311133-7475f400-9988-11e9-902e-1a35e3ce2efb.png)
![image](https://user-images.githubusercontent.com/44956625/60311138-80fa4c80-9988-11e9-8fec-bd0a743d7fab.png)
![image](https://user-images.githubusercontent.com/44956625/60311141-83f53d00-9988-11e9-86d2-e108ab090afa.png)
该交易已上链
已过期的交易在cache中未被删除

**Comment by icehawk-hyb** [comment]
问题分析：

1，这个交易本生已经上链，应该会在mempool模块收到EventAddBlock事件时将已经上链的所有交易从mempool中删除。

此时跳跃树存在误删除的情况，也就是在删除hash-a时误删除了hash-b在txList中对应的信息，同时删除了hash-a在txMap中的记录。

2，在删除hash-b时txList中已经不存在，只会删除hash-b在txMap中的记录。这样hash-b的交易信息在cache中完全被删除了。

3，而 hash-a交易的信息还存在cache的txList中，txMap中已经没有hash-a对应的记录了。

4，mempool list获取的是txList中存储的所有交易信息，此时没有被删除的hash-a的交易过期就不会显示出来，所以此时通过mempool list看到是空的。

5，有一个定时间检测交易是否过期的处理，检测到交易过期之后就会从cache中删除此交易。
此时检测到了这个存留在txList中已经过期的交易hash-a，并调用删除接口删除此交易。
在删除此交易时会判断这个交易是否存在cache中，通过txMap中是否有对应hash的记录来判断的，此时hash-a交易在txMap中记录已经被清除了。此时认为此交易不存在不再做删除的动作。


这样的话就会导致hash-a交易一致存在txList表中无法被删除。
