### ISSUE TITLE
NumGoroutine过高

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#561]
测试链节点运行时，NumGoroutine达到3w9，日志正常输出，节点命令无法调用
![image](https://user-images.githubusercontent.com/44956625/60788246-d1df2180-a18e-11e9-93bf-234d1e93885a.png)
[Uploading profile001.pdf…]()

**Comment by xies1031** [comment]
[chain33-2019-07-07T11-16-51.558.log.gz](https://github.com/33cn/plugin/files/3366970/chain33-2019-07-07T11-16-51.558.log.gz)
[Uploading chain33-2019-07-06T00-40-49.769.log.gz…]()

[Uploading chain33-2019-07-05T18-49-52.207.log.gz…]()

**Comment by vipwzw** [comment]
问题解决了吗？

**Comment by vipwzw** [comment]
需要引用一下解决这个问题的 pull request

**Comment by bysomeone** [comment]
之前p2p同步引起的goroutine过高是#581， 已经解决

本issue应该是更早的一个问题

**Comment by icehawk-hyb** [comment]
已经在chian33的这个pr中解决了  https://github.com/33cn/chain33/pull/616
