### ISSUE TITLE
【hashlock】一些问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#567]
1.目前hashlock合约，lock时对于secret的配置是唯一的，即：
A向B创建了一笔hashlock交易，设置的secret为AAA，此时若C向D创建了一笔hashlock交易，设置的secret也为AAA，则D无法通过send获取锁定的金额，C也无法通过unlock解锁这部分金额。
只有A与B之间的交易能够正常完成。此时C的那部分金额会一直处于冻结状态，无法解锁。

考虑改进成secret及双方地址的校验后唯一，不再独立唯一。且创建时判断该secret和AB双方地址是否已存在，避免重复。

2.目前创建hashlock的lock交易时，需要设置returnAddr，且需要与签名地址一致；建议去掉这个return地址的指向，直接使用签名地址即可。

**Comment by andyYuanFZM** [comment]
@harrylee2015  这个问题你帮忙看下。

**Comment by harrylee2015** [comment]
看了一下代码，在现有的hashlock合约中，secret 是唯一的,只能使用一次，下次就不能再使用了，不会存在用同一个secret去锁定两笔交易，如果同时发送两笔一样的secret去锁定，只有第一笔交易会被执行成功，后者会报hash重复了的错误，就是这个secret已经被人使用了。

**Comment by harrylee2015** [comment]
可以考虑在现有的设计方案之上，做个微调整，增加secret被释放后，可以重复使用。
hashlock的lock交易时，用户不需要填return地址，默认采用签名地址即可

**Comment by vipwzw** [comment]
现在的方案就是去掉了 return address 吗？

**Comment by harrylee2015** [comment]
是的，secret还是保留原来设计，不能重复使用

**Comment by xies1031** [comment]
那如果多次使用hashlock合约，用户在设定一些简单secret的时候会反复报重复的吧，会不会影响体验

**Comment by harrylee2015** [comment]
会的，这个感觉不可避免，要安全性好，secret必然只能使用一次，不然就存在泄露的风险。也可以增加一个hash检查接口，用于检查secret有没有被占用，不过这样就会多了一步，还是会影响用户体验的

**Comment by harrylee2015** [comment]
重新修改了一下，增加了一个fork，默认主链设置在300万高度，保留了returnAddress,   建议前端在包装时，可以先用secret去查询有没有实例，有得话，则需要重新换一secret,这样避免发送失败得交易

**Comment by xies1031** [comment]
> 重新修改了一下，增加了一个fork，默认主链设置在300万高度，保留了returnAddress, 建议前端在包装时，可以先用secret去查询有没有实例，有得话，则需要重新换一secret,这样避免发送失败得交易

主链上没有hashlock交易，不需要增加fork
测试链需要增加fork

**Comment by harrylee2015** [comment]
确定没有吗？我看比特元代码中把这个hashlock插件打进去了
![image](https://user-images.githubusercontent.com/18208851/61760972-d434b300-adff-11e9-98e1-96102928f36a.png)

**Comment by vipwzw** [comment]
加添加在这里吧，加一个fork 比较保险一点

**Comment by xies1031** [comment]
已修复
