### ISSUE TITLE
ticket close 命令 -m  选项无效

### ISSUE THREAD

**Issue by vipwzw** [33cn/plugin#572]
**Describe the bug**
root@iZbp111aakhteh68bgvlbqZ:~# ./chain33-cli ticket close -m 1NbLdeZYqdaYHFyjBu9evsAmBzfRpiQAZP
{
    "hashes": [
        "0x6d8f1ae23c11d6191b0dd7f4eab86bce0d787874dd89e845a825c6af38cff917"
    ]
}
close 的是这个机器另外一个挖矿地址

**Comment by vipwzw** [comment]
@mdj33  你看来一下这个问题

**Comment by mdj33** [comment]
在看

**Comment by mdj33** [comment]
好的
