### ISSUE TITLE
[unfreeze]冻结解冻合约增加相关cli命令

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#575]
unfreeze增加了部分rpc接口，需要补充对应的cli命令
目前本合约缺少部分查询接口，包括根据创建者地址查询合约id、根据受益人地址查询合约id。
@linj-disanbo

**Comment by vipwzw** [comment]
@linj-disanbo 处理的怎么样了？

**Comment by linj-disanbo** [comment]
> @linj-disanbo 处理的怎么样了？

#600 处理后处理

**Comment by linj-disanbo** [comment]
已经有了 在 2019年1月加的
$ ./build/chain33-cli  unfreeze list -x
Error: unknown shorthand flag: 'x' in -x
Usage:
  -cli unfreeze list [flags]

Flags:
  -b, --beneficiary string   list by beneficiary
      --count int32          list count (default 10)
  -c, --create string        list by creator
  -d, --direction int32      list direction: 0/1
  -h, --help                 help for list
  -l, --last_key string      last key

**Comment by linj-disanbo** [comment]
@xies1031  是上面的功能吗， 是的话， 可以关闭了
