### ISSUE TITLE
[trade]token_assets未返回正确余额

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#586]
使用trade合约购买一个trade挂卖单后，使用token_assets查询token余额不正确
![image](https://user-images.githubusercontent.com/44956625/62522505-6c9d4f80-b864-11e9-82f3-64287f81daf1.png)

![image](https://user-images.githubusercontent.com/44956625/62522486-6313e780-b864-11e9-94e9-1c9aa093ac0d.png)
使用token_balance能够正确查询出结果
![image](https://user-images.githubusercontent.com/44956625/62522544-7aeb6b80-b864-11e9-96e6-4d23b670a9c5.png)

另外一个地址使用token send_exec从token合约向trade合约转移token后使用token_assets查询，能够正确返回余额
![image](https://user-images.githubusercontent.com/44956625/62522620-a2423880-b864-11e9-9c94-58bc66946811.png)
@linj-disanbo

**Comment by vipwzw** [comment]
@linj-disanbo  处理的怎么样了

**Comment by linj-disanbo** [comment]
token_assets 这个命令是需要token合约下有过对应资产后才能查到

 在第一种case 的情况下， 需要提币回token 合约才能查到。 

 一个帐号是否有某种token， 原来是在其他合约里嵌入代码的， 增加对应合约有某类token。 在某个版本后，去掉了跨合约写数据(local的)， 导致这个功能是这种现状。 同时去掉的有 token的交易列表， 原来在 trade 合约里 有相关的 token交易， 对应交易也列在token的交易列表。

 @vipwzw  这个功能是否就保持现状。

**Comment by linj-disanbo** [comment]
先保持现状
