### ISSUE TITLE
[unfreeze]在获得unfreeze信息时， 希望包括终结合约的时间

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#587]
终结合约的时间在app上有用。 现在需要在获得 unfreeze 信息后， 状态是终结的， 在扫码出终结合约的交易， 取这个交易的打包时间。 这个过程比较麻烦。 

希望在 ListUnfreezeByCreator/GetUnfreeze/ListUnfreezeByBeneficiary 接口加上这个信息

**Comment by vipwzw** [comment]
处理的怎么样了？

**Comment by linj-disanbo** [comment]
> 处理的怎么样了？

#600 处理后处理

**Comment by linj-disanbo** [comment]
这个功能做到本地代码库了， 做外定制功能， 是否需要合并 @vipwzw
