### ISSUE TITLE
[unfreeze]增加解锁的计算方式

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#588]
**Is your feature request related to a problem? Please describe.**
项目需求。项目上线预期 20天。 

解锁方式： 
 1. 按总额度的比例计算每期解锁量。
 1. 比例按一定的周期递减。如每200次解锁后， 比例为上次比例的 90%
 1. 比例递减 N 次后不再递减

数据举例：10000总量， 比例 1%， 递减周期 10， N = 2
 预期解锁过程：
 1.  前10次按1% 即 每次解锁100。包含生成合约时的那次解锁。
 1. 第11～20次， 比例为 1%×90%=0.9% 解锁 即 每次解锁 90。
 1. 第21～30次为：比例为 0.9% * 90% = 0.81% , 即 每次解锁 81. 
 1. 比例递减次数N达到 2。 计算后续比例 0.81% * 90% = 0.729%。 之后比例不变
 1. 31次以及之后： 比例为 0.729% ，直到解锁完所有的锁定币

**Describe the solution you'd like**

在创建合约试，增加一种解锁方式。 并实现新的解锁计算的函数， 加上rpc

**Comment by vipwzw** [comment]
暂时我们的官方合约不添加这些功能。
