### ISSUE TITLE
[privacy]隐私合约相关问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#590]
1.支持多合约代币相关：
目前命令中，showau及showutxo4a两个查询命令未支持其他合约代币查询，仅能查询BTY；
showpai和showpas的查询key不带执行器，直接通过symbol查询，后续需要改动与执行器配合查询。
2.rescanOpt加载导入地址的UTXO不生效
![image](https://user-images.githubusercontent.com/44956625/62856260-fea2cd80-bd26-11e9-889d-cd105b2d7720.png)

**Comment by bysomeone** [comment]
钱包utxo管理后续统一安排处理

**Comment by vipwzw** [comment]
pr 处理的地方，引用一下这个issues

**Comment by bysomeone** [comment]
这个还没提pr
