### ISSUE TITLE
【plugin】发送交易执行成功后，日志返回错误

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#592]
plugin代码，发送交易，并执行成功，日志返回错误 
![image](https://user-images.githubusercontent.com/44956625/63245936-09fc7880-c294-11e9-8bd5-89f0c1da4c60.png)
因代码中存在两处wrong tx打印，增加打印后发现是里面的错误打印
![image](https://user-images.githubusercontent.com/44956625/63246086-68295b80-c294-11e9-8615-929209f260fd.png)

**Comment by vipwzw** [comment]
怎么复现这个问题，每笔交易都有这个错误吗？

**Comment by xies1031** [comment]
> 怎么复现这个问题，每笔交易都有这个错误吗？

是的，每一笔交易都会返回这个错误
