### ISSUE TITLE
trade 合约可以用任意的币标记价格

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#600]
**Is your feature request related to a problem? Please describe.**
trade 合约可以用任意的币标记价格，可以实现任意资产对的交易

**Comment by vipwzw** [comment]
不能用自己的币标记

**Comment by vipwzw** [comment]
比如 bty/bty 不允许

**Comment by linj-disanbo** [comment]
原来最老的rpc接口， 保留能获得 coins 标价的订单。 
新的rpc 接口提供默认值为 coins 标价的订单， 增加参数可以指定 标价的资产

**Comment by linj-disanbo** [comment]
> 不能用自己的币标记

谢谢提醒。 
有做判断
