### ISSUE TITLE
【addroverview查询结果有误】

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#605]
plugin部分节点addr_overview查询结果有误
![image](https://user-images.githubusercontent.com/44956625/63989101-b26ed000-cb11-11e9-943d-4cc5e077cb5a.png)
查询有7笔交易
![image](https://user-images.githubusercontent.com/44956625/63989106-b864b100-cb11-11e9-9eeb-b5d6c0fb5927.png)
实际为5笔交易
![image](https://user-images.githubusercontent.com/44956625/63989114-c61a3680-cb11-11e9-84ce-6f3632ad55cb.png)
正常节点为5笔交易

**Comment by xies1031** [comment]
从0同步了一个节点查询后正常

**Comment by icehawk-hyb** [comment]
这个问题目前通过测试发现是在升级storedb时使能EnableReExecLocal功能重新执行AddTxs引起的。
此时执行AddTxs会使得交易统计性的计数增加。导致计数翻倍。比如记录地址交易数量的计数。因为交易计数性的数据都是AddTxs时增加，DelTxs时减少的   。 @lyh169

**Comment by lyh169** [comment]
> 这个问题目前通过测试发现是在升级storedb时使能EnableReExecLocal功能重新执行AddTxs引起的。
> 此时执行AddTxs会使得交易统计性的计数增加。导致计数翻倍。比如记录地址交易数量的计数。因为交易计数性的数据都是AddTxs时增加，DelTxs时减少的 。 @lyh169

升级storedb时使能EnableReExecLocal这个是针对合约中使用localdb数据，需要是能；
是能情况下这由于blockchain中交易计数是累加计数的，所以重新执行时候原来交易还会累加；
