### ISSUE TITLE
【共识插件】在plugin中实现hotstaff共识插件

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#612]
参考hotstaff论文以及libra共识协议的实现， 制定方案，在chain33中实现类似的共识插件。

**Comment by andyYuanFZM** [comment]
@caoping33

**Comment by caopingcp** [comment]
LibraBFT实现分析：https://gitlab.33.cn/caoping/share/blob/master/chain33/LibraBFT%E5%88%86%E6%9E%90.md

**Comment by andyYuanFZM** [comment]
这个投入时间可能会比较长。   目前先研究在tendermint中引入聚合签名，来优化共识逻辑。

**Comment by andyYuanFZM** [comment]
使用 #774 跟踪，这个issue先关闭。
