### ISSUE TITLE
【Tendermint共识】稳定性测试中，发现共识有概率会卡住

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#615]
@caoping33

**Comment by caopingcp** [comment]
日志显示 proposer 节点打包完一个新区块后，其他节点没有及时收到该区块，可能是P2P模块出现问题。由于其他节点跟 proposer 节点区块高度差 1，blockchain模块不能自动同步到最新高度，导致其他节点的共识不能进入下一个高度。
目前的临时解决方法是：修改blockchain模块，当高度差1时，也可以自动同步区块

**Comment by andyYuanFZM** [comment]
当时讨论，在共识模块和blockchain之间增加通知消息。 DPOS和tendermint或是后面的hotstaff共识应该都能用得到。  
@caopingcp @zzh33cn  后面讨论下，看看需要增加哪些消息通信，到时提个需求。

**Comment by vipwzw** [comment]
@caopingcp 难道一个节点坏了，就不能达成共识了吗？blockchain 如果 p2p 没有成功通知，是会去其他节点主动要数据的。没有明白为什么你说的情况会发生卡住。

**Comment by caopingcp** [comment]
> @caopingcp 难道一个节点坏了，就不能达成共识了吗？blockchain 如果 p2p 没有成功通知，是会去其他节点主动要数据的。没有明白为什么你说的情况会发生卡住。

出现的问题是只有 proposer 节点没问题，其他所有节点没有收到最新的区块，而因为其他节点跟 proposer 节点区块高度只差 1，blockchain 模块没有自动同步区块（https://github.com/33cn/chain33/blob/master/blockchain/blocksyn.go#L584），这样导致其他节点都落后1个区块，从而共识卡住了

**Comment by vipwzw** [comment]
这块的问题就近期修复了吧，放到 6.3 版本修复，截止日期 9月20日
