### ISSUE TITLE
plugin代码，升级stateDB版本panic

### ISSUE THREAD

**Issue by flyaway53** [33cn/plugin#616]
修改plugin代码的stateDB版本号升级，升级中内存会溢出导致panic
![image](https://user-images.githubusercontent.com/28993758/64149459-87111b80-ce58-11e9-8958-2899f2fbc59c.png)
![image](https://user-images.githubusercontent.com/28993758/64149499-a019cc80-ce58-11e9-80b2-e0dd03d1c38b.png)

**Comment by icehawk-hyb** [comment]
两个问题：
1，在升级localdb时删除了保存storedb版本信息的kv对，导致升级完localdb之后都会再次升级storedb；

问题修改：
在version.go文件中将StoreDBMeta的key值添加到 GetLocalDBKeyList中，这样在升级reindex时就会过滤出这个key值从而不会删除
![image](https://user-images.githubusercontent.com/44956735/64233757-81363b80-cf27-11e9-827e-22f7146dd140.png)


2，在升级storedb时由于从0高度开始重新执行。导致kvmvcc checkVersion不过。此时就会从当前的最新高度开始删除数据，而此时删除的数据都会缓存到cache中，这样的话，就是导致删除几百万高度的数据时内存不够挂死。

日志记录：
![image](https://user-images.githubusercontent.com/44956735/64233858-b80c5180-cf27-11e9-9d4e-a05c26308c99.png)

@lyh169

**Comment by lyh169** [comment]
@vipwzw 第二个问题，之前删除了kvmvcc 内部的回滚限制导致的，目前blockchain这里最大回滚深度为10000，，，那这种情况需要再加回去，比如kvmvcc内部设置最大回滚深度10000+1024
