### ISSUE TITLE
[autonomy V2]相关问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#623]
1.proposalChange时，已屏蔽的董事会成员依然可以参与投票，未过滤已屏蔽的地址
2.proposalProject申请时，申请非法的金额时，返回的错误信息有误
![image](https://user-images.githubusercontent.com/44956625/64667455-7aaa4580-d48c-11e9-82b0-14af91fa14c2.png)
![image](https://user-images.githubusercontent.com/44956625/64667477-8138bd00-d48c-11e9-9e7a-ba437b96a7bb.png)
设置为负值时也能进入执行，应在cli中限制负值的输入
![image](https://user-images.githubusercontent.com/44956625/64667828-c14c6f80-d48d-11e9-9019-9ec693641222.png)

3.proposalProject申请时，projectNeedBlockNum字段未做限制，传0及负数时执行成功，建议限制为大于0.
![image](https://user-images.githubusercontent.com/44956625/64667848-d9bc8a00-d48d-11e9-8476-041253abe21c.png)

**Comment by lyh169** [comment]
2、输入负值应该提案会失败吧 ？
3、中projectNeedBlockNum只做展示用，没有实际意义，需要外部董事会进行跟踪项目状态

**Comment by vipwzw** [comment]
为什么会出现负数的情况？

**Comment by xies1031** [comment]
https://testnet.bityuan.com/tradeHash?hash=0x989e60204fbd97784d624f8d602c309813cf719d43f3c8dc0668a20a18e5ff1a
"projectNeedBlockNum": -10
其余负数输入执行的时候会判断失败
就算是只做展示最好也先把非零的判断掉
这个输入负值的提案成功了
