### ISSUE TITLE
【retrieve】相关

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#639]
1.找回token时，perform未传入token的asset
![image](https://user-images.githubusercontent.com/44956625/65404303-94437980-de0a-11e9-9e7a-4c7d5f5a10af.png)
![image](https://user-images.githubusercontent.com/44956625/65404308-99a0c400-de0a-11e9-8882-85b3d29a8baa.png)
导致找回token失败
2.新增的查询命令未增加cli
3.retrieve query cli相关解释有误
![image](https://user-images.githubusercontent.com/44956625/65404377-c94fcc00-de0a-11e9-8ab8-8a0e5f947db2.png)

@linj-disanbo

**Comment by linj-disanbo** [comment]
1. rpc的问题，客户端有传参数 

2 查询命令增加参数

```
Usage:
  -cli retrieve query [flags]

Flags:
  -e, --asset_exec string     asset exec
  -s, --asset_symbol string   asset symbol
  -b, --backup string         backup address
  -t, --default string        default address
  -h, --help                  help for query

```

3.  修复提示

4. rpc test fix
