### ISSUE TITLE
多重签名合约的解析 - 需要增加状态字段

### ISSUE THREAD

**Issue by yanchenta** [33cn/plugin#680]
多重签名账户的状态(可用/修改中/转帐中)，需要做全网的状态查询。

**Comment by icehawk-hyb** [comment]
只要创建了应该就是可用的。
修改和转账中状态可以通过获取指定多重签名地址下pending交易然后判断交易类型就可区分了。

或者通过外部数据库展开多重签名合约的交易就可以统计出来了

这个不需要在合约中再单独实现来存储，反而增加数据库的负担。
@yanchenta
