### ISSUE TITLE
cli evm create 相关交易需要增加gaslimit等参数的设置

### ISSUE THREAD

**Issue by harrylee2015** [33cn/plugin#705]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vipwzw** [comment]
现在默认多少

**Comment by harrylee2015** [comment]
> 现在默认多少

现在默认是 设置的交易手续费，比如 fee 设置为0.1 的话，gaslimit 就是 0.1 * 1e8= 10000000

**Comment by harrylee2015** [comment]
试了一下应该只需要调整一下 fee  设置，目前看，是设置fee 的参数不生效，估计是做了一次tx.format, 这块可能需要调整一下

**Comment by harrylee2015** [comment]
命令行中fee 参数设置不生效，调一下这里就可以
