### ISSUE TITLE
ERC777 ERC20 ERC1410

### ISSUE THREAD

**Issue by vipwzw** [33cn/plugin#71]
token 合约实现类似 ERC20 ERC777 以及 ERC1410 的功能.

按照名称前缀，配置相关功能权限。

没有前缀，基本的token功能

定义前缀S
S: 1410 sto 相关的币

显示的时候可以这样 S:FZM -> FZM(股权)

**Comment by linj-disanbo** [comment]
1. 在币的操作方便，可以增加铸币、燃烧功能
 1. 增加对部分同质token的支持，增加对现实资产的建模能力

**Comment by vipwzw** [comment]
方案有变化。
