### ISSUE TITLE
平行链配置文件需要一份配置模块及核心配置项的注释

### ISSUE THREAD

**Issue by harrylee2015** [33cn/plugin#711]
目前平行链的配置项比较多，有些配置项在特定的链上是不同的，不能随意改动，不然容易出现一些意想不到的情况，需要加注释说明一下

**Comment by vipwzw** [comment]
@mdj33  现在我们弄了一个解决方案，平行链的配置统一管理，通过软件工具对平行链配置进行升级。

**Comment by vipwzw** [comment]
到时候可以一起讨论一下，方便客户使用，升级平行链对配置。尽量避免手工对改动。

**Comment by mdj33** [comment]
https://gitlab.33.cn/zjf33/parachainconf

**Comment by vipwzw** [comment]
@mdj33  这次的升级能保证用户不用怎么修改配置文件吗？是不是要同步一下配置文件，然后统一修改

**Comment by mdj33** [comment]
@vipwzw 这次升级配置文件也有一些修改，不过影响都不大，是一些优化，比如大小写统一和分叉添加，但是还是要统一修改下，我发现用自动化脚本修改配置文件还是不是很靠谱，　有些配置项还是确认过之后比较好，自动化修改没想到特别好的办法
