### ISSUE TITLE
raft 共识日志精简

### ISSUE THREAD

**Issue by caopingcp** [33cn/plugin#723]
raft 共识将区块写入日志，造成数据冗余，需要精简，同时要考虑状态恢复

**Comment by vipwzw** [comment]
writeblock 的时候，区块会被写入区块链，就算被回滚，这个区块也不会被删除。所以，可以利用这个特点，只保存日志就可以了，需要完整的区块直接从blockchain 中读取。

**Comment by caopingcp** [comment]
@vipwzw @andyYuanFZM 
方案如下：
1. leader 节点满足一定条件（参考第3点）后在指定高度开始打包，先调用 writeblock 将区块写入到 blockchain 模块，然后调用 Propose 对（区块高度，区块哈希）这一信息发起提议，同时 follower 节点会接收到 leader 广播的区块，并打包
2. leader 和 follower 节点在共识中判断 **提议信息 rd.Entries** 对应的区块是否写入到 blockchain 模块，如果是就将提议信息写到 WAL 日志中，同时将 **达成共识的信息 rd.CommittedEntries** 保存在内存中
3. leader 节点将 **达成共识的信息** 与 blockchain 模块的最新区块的高度和哈希进行比较，如果相同则开始打包下一个高度的区块，否则继续等待

存在问题：
1. leader 节点需要等到 **达成共识的信息**  才打包下一个高度的区块，这会降低打包速度，可以将第3点中改成 **提议信息** 来提高，不过可能影响共识的正确性
2. follower 节点要等到接收并打包区块才写 WAL 日志，影响 raft 共识效率
