### ISSUE TITLE
实现一个通用的存证合约

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#729]
目前市场上对存证有一些需求，所以打算支持一套相对通用的存证合约（合约和JAVA-SDK都要增强），来简化外部的应用。包括但不限于以下功能：
1.  内容存证（内容本身）
2.  hash存证（文件hash,内容hash，链接）
3.  隐私存证（只能自己看，对称加密存证）
4. 可分享的隐私存证。

**Comment by andyYuanFZM** [comment]
@harrylee2015  这个需求看 一下。

**Comment by harrylee2015** [comment]
https://github.com/harrylee2015/plugin/blob/storage/plugin/dapp/storage/proto/storage.proto
存证的相关数据模型，目前有五种基本的数据模型，dapp,主体开发基本结束，后面可以根据需求进行微调，剩下单元测试和框架测试用例待补充

**Comment by linj-disanbo** [comment]
存证一定要存在状态数据库吗？ 个人觉得， 上链到账本也一样
