### ISSUE TITLE
【多重签名】使用cli查询和rpc查询返回结果不一致

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#744]
使用cli查询地址详情与使用rpc查询，两者返回不一致
![image](https://user-images.githubusercontent.com/44956625/70976881-b84fe780-20e7-11ea-9cea-cf4f1846d7e4.png)
![image](https://user-images.githubusercontent.com/44956625/70976958-dd445a80-20e7-11ea-900b-9f9f38350449.png)

@icehawk-hyb

**Comment by icehawk-hyb** [comment]
这个不是问题，是在通过rpc接口创建时，币的数量没有乘10的8次方导致的。我们cli只显示小数点后4位
