### ISSUE TITLE
平行链和主链之间的币的转移

### ISSUE THREAD

**Issue by vipwzw** [33cn/plugin#758]
**币资产在平行链之间转移**

币或者说资产，都有全局唯一的名字，但是，转移到非自己链上之后不是真的资产过去了，而是在另外一条链上发行了一个新的资产。

主链转平行链，实际上是主链的资产冻结，在平行链上发行了一个新的币，比如coins.BTY 转移到了 test 链，这个币的合约名字为 user.p.test.paracross 币的名称为 coins.BTY

平行链转主链，实际上是平行链的资产冻结，在主链上发行了一个新的币 和他对应，比如user.p.test.coins 这个币，到主链上之后变成了一个合约为paracross 名字为 user.p.test.coins 的币。所以实际的币名称为 paracross.user.p.test.coins

同时这个币，这个币 作为一个主链币，可以用 主链币 转 平行链的方法转移到其他平行链上去。
 
唯一有变化的地方是，需要添加一条规则：

```
如果 A 链的币，从其他链回到 A 链，那么做一个特殊的处理，A链解冻币，其他链的资产直接销毁。
```
具体的说：

>如果一个币是主链币，从平行链转移到主链的时候，区块链上需要做特殊的处理，也就是销毁在平行链上的主链币，然后再主链上解冻这个币。

>同样的，一个平行链的币，从主链转移到 自己的这个平行链，也是要做特殊处理，销毁主链的币，平行链自己链上解冻。

**Comment by mdj33** [comment]
是否再加两条规则：
2,如果在主链上一个币是平行链币，从主链转移到平行链时候，也需要特殊处理，销毁在主链上的平行链币，在平行链上恢复等额的币，也就是主链上paracross.user.p.test.coins.ccny  需要销毁，平行链上需要释放。
注意：这里在主链上的平行链的币**不能当做主链资产再转移到平行链**，也就是不能再在平行链user.p.test.paracross下产生新币paracross.user.p.test.coins.ccny. 同理，一个在平行链上的主链币，也不能当做平行链的资产转移到主链。也就是paracross合约下的币要特殊处理，转移进来的币不能当做资产

3. 如果一个币是test平行链币，转移到主链上是paracross.user.p.test.coins.ccny, 然后再转移到para平行链，则为user.p.para.paracross 执行器下的paracross.user.p.test.coins.ccny
如果从para平行链转移回主链，也是销毁user.p.para.paracross下的paracross.user.p.test.coins.ccny ,然后在主链paracross下恢复等额的user.p.test.coins.ccny

**Comment by vipwzw** [comment]
平行链的币转移到主链，肯定是发了一个主链币，这个币就是可以当作普通的主链币转移到平行链上的。
