### ISSUE TITLE
本地数据库精简后， 部分合约的查询接口不可用

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/plugin#762]
**Describe the bug**

合并新的chain33后，部分合约的查询接口在测试不通过。 

原因： 
 1. 部分查询的数据在被精简的数据库部分, 是通过索引， 执行执行结果的receipt 日志， 而执行结果的receipt 日志是本地数据库精简掉的数据。
 1. 测试逻辑依赖receipt  

这部分接口重新实现。 在本地db中保存， 查询时就查询合约自身保存的数据， 不依赖执行日志。并调整测试

**To Reproduce**
make docker-compose 

```
http://168.63.134.210:8080/blue/organizations/jenkins/chain33-plugin/detail/chain33-plugin/1546/pipeline/
```
**Expected behavior**
 可以测试通过

**Comment by linj-disanbo** [comment]
发现合约不可用在这里列出

 1. unfreeze  test-rpc 测试失败， 逻辑依赖receipt 日志
 1. trade  查询panic

**Comment by vipwzw** [comment]
evm的也对应做一个修改，应该把需要查询的值保存到localdb 就可以了
