### ISSUE TITLE
autonomy合约rpc测试不能通过

### ISSUE THREAD

**Issue by yann-sjtu** [33cn/plugin#785]
![image](https://user-images.githubusercontent.com/29310615/73738451-722a1280-477f-11ea-8825-e781f3cda09f.png)

**Comment by lyh169** [comment]
是哪个pr呢？必先吗

**Comment by yann-sjtu** [comment]
> 是哪个pr呢？必先吗

#783，我修复了一下evm合约的rpc测试代码，测试是ok的，昨天合并了一下master又提交，然后autonomy就报错了

**Comment by lyh169** [comment]
> > 是哪个pr呢？必先吗
> 
> #783，我修复了一下evm合约的rpc测试代码，测试是ok的，昨天合并了一下master又提交，然后autonomy就报错了

新的代码，我这边本地测试了5 6次，也没有出现，783的那个打不开。等之后遇到了再看看吧。

**Comment by yann-sjtu** [comment]
> > > 是哪个pr呢？必先吗
> > 
> > 
> > #783，我修复了一下evm合约的rpc测试代码，测试是ok的，昨天合并了一下master又提交，然后autonomy就报错了
> 
> 新的代码，我这边本地测试了5 6次，也没有出现，783的那个打不开。等之后遇到了再看看吧。

下午我又重新提交了一下测试又通过了，可能不是必现的，那这个issue先关了
