### ISSUE TITLE
Tendermint端口切换

### ISSUE THREAD

**Issue by caopingcp** [33cn/plugin#789]
Tendermint共识网络使用46656端口，如果该端口被占用，切换成其他端口号

**Comment by caopingcp** [comment]
Tendermint共识网络是由所有共识节点同时启动而建立的，如果允许切换端口，各个节点可能无法得知对端的端口号，从而无法建立共识网络。
建议关闭该 issue

**Comment by andyYuanFZM** [comment]
目前还没有机制在端口切换时，同时通知其它共识节点。 所以节点端口切换确实可能会导致共识失败。
先关闭此issue。
