### ISSUE TITLE
平行链跨链代码优化

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#794]
测试中发现问题修改

**Comment by chainseed** [comment]
详细一点列一下

**Comment by mdj33** [comment]
１，AssetTransfer/AssetWithdraw　分叉增加了需要配置nodegroup的约束，由于分叉只对主链有效，平行链分叉高度为０，这样在实际分叉前也就是6.4分叉前的平行链也会检查nodegroup配置，和老版本不一致，这样老版本没有配置nodegroup的平行链转移会失败。　修改后，只针对主链做nodegroup的约束检查，主链和平行链配置一致，主链通过平行链自然通过，主链不过，平行链也不会执行相关交易
２，crossAssetTransfer平行链增加了对6.４分叉前的错误处理，新的crossAssetTransfer功能不能在6.4分叉前执行，如果执行，主链是none执行器pack，平行链如果升级了会过滤执行到相关交易，不是期望的

以下是优化代码
３，nodegroup配置，当前平行链也需要配置和主链一样的superManager，其实只要在主链控制就可以，approve操作，如果主链通过了，自然是superManger的交易，平行链不需要判断，执行就可以，如果主链没通过，平行链也不会执行交易
４，新的平行链按表下载默认打开
