### ISSUE TITLE
开启最优区块的辅助比较功能

### ISSUE THREAD

**Issue by icehawk-hyb** [33cn/plugin#802]
**Is your feature request related to a problem? Please describe.**
当同一高度有多个区块时，开启最优区块的辅助比较功能。让整个网络基于同一个区块继续挖矿
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vipwzw** [comment]
这个问题解决了吗？

**Comment by icehawk-hyb** [comment]
这个issues的代码已经合入了可以关闭了：https://github.com/33cn/plugin/pull/803
