### ISSUE TITLE
【ticket】部分用户挖矿出现已关闭的ticket反复请求关闭的问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#836]
部分用户升级到6.4.0后，挖矿过程中出现反复请求关闭已关闭的ticket的问题。
查询这些ticketID后发现状态为已关闭。
![image](https://user-images.githubusercontent.com/44956625/78453169-91331b00-76c2-11ea-910c-a807fbf22751.png)
![image](https://user-images.githubusercontent.com/44956625/78453180-a14afa80-76c2-11ea-991b-1fbe5afe7a49.png)
Addr：1CR45k6CQaLBbqKh81NPrRgz3hrnbyQkMY

**Comment by mdj33** [comment]
在升级6.4.0期间，造成分叉的情况比较多，可能客户正好在侧链上挖矿，并且挖到了，但是在主链上ticket已经close过了，导致主链上收到close交易而出错。 后来客户没有再反馈这个问题了。
