### ISSUE TITLE
将auto_mine 置1后，automining状态未改变

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#85]
![image](https://user-images.githubusercontent.com/44956625/49074402-8f0bb180-f26f-11e8-891e-b734220c905b.png)
如图将auto_mine 置1后，automining状态未改变为true

**Comment by vipwzw** [comment]
@chain33-shg

**Comment by linj-disanbo** [comment]
bug原因：向钱包注册状态回报 RegisterMineStatusReporter 函数 实现时需要钱包已经完成初始化， 才能注册回报成功。 但钱包是在构造过程中(即没有完成初始化)，就注册状态回报 。 向钱包注册状态回报是钱包加载各种业务的一部分。 
修改：倾向于去掉注册时的限制。 （ 如果选择在钱包已经完成初始化， 再注册业务，则意味著钱包初始化后， 部分业务不可用。 ）
