### ISSUE TITLE
更新到最新版本后cli version显示为6.0.1

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#86]
![image](https://user-images.githubusercontent.com/44956625/49077945-9df66200-f277-11e8-8280-f39f07d8bb4c.png)
更新到最新版本后cli version显示为6.0.1
实际最新版本应为6.0.2

**Comment by vipwzw** [comment]
现在实际上有三个版本，一个版本号是配置文件配置的 app-version ，一个是 chain33-version,  还有一个 localdb version 这个我来处理一下，修改一下 version 这个命令行的接口，把这几个版本号都返回。

**Comment by vipwzw** [comment]
move to  ： 33cn/chain33#117
