### ISSUE TITLE
plugin代码同步问题

### ISSUE THREAD

**Issue by xies1031** [33cn/plugin#869]
同步至10001高度后停滞。日志中未继续执行10002区块，log中报错
ChunkRecordSync FetchChunkRecords
![image](https://user-images.githubusercontent.com/44956625/85982702-dd1f0300-ba18-11ea-9651-4518033141ff.png)

![image](https://user-images.githubusercontent.com/44956625/85982520-94674a00-ba18-11ea-8fe8-21d560bb996f.png)

**Comment by xies1031** [comment]
配置文件中缺少了配置项，blockchain 配置项 加一个 disableShard=true  关掉分片功能后解决

**Comment by xies1031** [comment]
同步至4140014，执行失败，状态哈希校验不过
![image](https://user-images.githubusercontent.com/44956625/86091481-9267be80-bade-11ea-98e2-0355e480e69b.png)
![image](https://user-images.githubusercontent.com/44956625/86091504-9d225380-bade-11ea-81b5-70a2d9b0a491.png)
@mdj33

**Comment by mdj33** [comment]
是exec cache 修改导致的问题，不是nodegroup本身的问题，测试链已经全部同步完成
