### ISSUE TITLE
mempool 删除大量交易缓存速度较慢

### ISSUE THREAD

**Issue by caopingcp** [33cn/plugin#889]
4个节点组成 tendermint 集群，每个节点依次循环打包区块，其中 mempool 排序策略为 timeline 方式
当每个节点每秒钟收到1000笔交易时，出现 节点需要等待4，5秒才能获取到新的交易
初步判断是节点打包区块后通知 mempool 删除其交易缓存的速度较慢

**Comment by bysomeone** [comment]
### 原因分析


1. 目前mempool通过AddBlock通知，删除已打包交易，该通知采用了异步低速发送模式，low通道

2. mempool模块同时在并发处理新交易，采用的是高速模式，high通道

3. high通道消息优先处理，导致addBlock消息随着时间，会累积越来越多，不能得到及时处理，即mempool的block header信息一直落后实际打包区块，高度差越来越大

4. 本地发送的交易采用txHeight高度过期，当高度差超出txHeight设置的最低高度，目前是30，新加入的交易被认为是过期交易，不会添加进缓存池，导致一段时间内本地无法获取新交易


```go

select {
			case data, ok := <-sub.high:
				if client.isEnd(data, ok) {
					qlog.Info("unsub1", "topic", topic)
					return
				}
				client.Recv() <- data
			default:
				select {
				case data, ok := <-sub.high:
					if client.isEnd(data, ok) {
						qlog.Info("unsub2", "topic", topic)
						return
					}
					client.Recv() <- data
				case data, ok := <-sub.low:
					if client.isEnd(data, ok) {
						qlog.Info("unsub3", "topic", topic)
						return
					}
					client.Recv() <- data
				case <-client.done:
					qlog.Error("unsub4", "topic", topic)
					return
				}
			}


```

![image](https://user-images.githubusercontent.com/11565373/88391148-2f6efc00-cdec-11ea-8f2e-cdd28c7274ab.png)


### 修改方法

发送Addblock消息采用高速模式，在环境上跑了1w个区块，没有发现类似现象，mempool 区块和实际打包高度保持一致
