### ISSUE TITLE
平行链p2p PubSub功能不是特别稳定

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#899]
p2p pubsub 功能在内网节点发现上很慢，可能要1天多， 外围节点ip 也需要多测试，影响了平行链聚合签名的使用

**Comment by libangzhu** [comment]
已经解决，libp2p pubsub需要在网络发生连接之前进行初始化
fix 33cn/chain33#940

**Comment by mdj33** [comment]
已解决
