### ISSUE TITLE
增加混币合约

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#918]
基于零知识证明的混币合约
1. 用户deposit 资金到合约，同时产生一个commit hash 代表的note，这个note是用户指定的账户才可消费
2. 指定账户可以在合约里面转账到其他账户，合约通过零知识证明验证用户对此note有花费权限，对外不可见
3. 用户可以花费一个note，从合约里面withdraw资金出来
4. 混币交易最终将采用代理方式发送，防止追踪，同时代理收取一定佣金

**Comment by vipwzw** [comment]
合约部分可以先提交，后面再提交wallet 模块。
