### ISSUE TITLE
[EVM合约]平行链场景下，EVM合约不支持走代扣交易

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#924]
我们代扣交易的实现是，将实际交易和代扣交易放一个group中， 同时将实际交易体中的fee置为0。
而对于evm合约，EVM虚拟机在计算GAS的时候是需要这个fee的。 当fee是0的时候，会报out of gas的错误，导致交易执行失败。

可能的解决方案：
修改EVM虚拟机中GAS这块的逻辑，让fee为0的时候也会通过。  
这种方案存在的风险： 因为合约是动态部署，如果有死循环逻辑，可能会导致整条平行链出问题。

**Comment by vipwzw** [comment]
1. 交易在执行的时候，是可以读取到整个 group的交易的，如果fee 为 0，那么就去 txs[0] 的 fee

**Comment by vipwzw** [comment]
参考这个函数：
https://github.com/33cn/chain33/blob/e2d7705ea4536ca18fe81413f4026503cde97efc/system/dapp/driver.go#L71

**Comment by andyYuanFZM** [comment]
OK
