### ISSUE TITLE
节点重启后，要频发发送 checkExpireFTXOOnTimer Can not get last header 的错误日志

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/plugin#950]
当节点程序停止再开启时，日志报错，重新发笔交易日志正常
日志不断报错，可能会影响链的运行维护者。

过程：
1 pkill chain33
2 chain33 –f chain33.toml
会在日志不断输出错误， checkExpireFTXOOnTimer Can not get last header. module=wallet.privacy

**Comment by vipwzw** [comment]
@bysomeone  修复一下
