### ISSUE TITLE
权限控制

### ISSUE THREAD

**Issue by vipwzw** [33cn/plugin#955]
1. 提供一个合约，在链上保存证书信息。

2. 如果mempool 开启证书检查开关，那么如果CheckTx 中，证书不正确的交易要被拒绝加入mempool

3. 可以根据不同的平行链来检查不同的证书。

**Comment by jpeng-go** [comment]
证书工具支持生成中间证书

**Comment by vipwzw** [comment]
> 证书工具支持生成中间证书

需要修改代码吗

**Comment by jpeng-go** [comment]
> > 证书工具支持生成中间证书
> 
> 需要修改代码吗

要的，正在修改，本周可以完成
