### ISSUE TITLE
Makefile的build指令引用了GOPATH中的包，会导致CI中潜在的编译错误

### ISSUE THREAD

**Issue by litian33** [33cn/plugin#96]
**问题描述：**
在本地Makefile编译工程时，会从GOPATH和vendor两个目录下查找依赖的包，CI环境上的GOPATH内容未知，可以认为编译仅依赖vendor内容，这样会导致一个潜在问题：

> 本地开发代码时引入了GOPATH中的包，在本地编译、打包、测试都是正常的，但是向Github提交代码时ci失败，因为vendor中没有此包；

**建议解决方案：**
方案一：
升级到Go111版本，启用module开关，通过go.mod管理依赖关系；

方案二：
修改Makefile，build指令中避免引用GOPATH中的包；

**Comment by 33cn** [comment]
提交代码前，可以运行一下。
```
govendor add +e
```
可以自动复制引用的 包到vendor 中。
目前考虑到包到需要翻墙下载和go.mod 的成熟度的问题，暂时不会直接升级 go1.11

**Comment by vipwzw** [comment]
这个问题很难解决。我在开发的过程中很少碰到这样的情况。目前也只能看ci日志来解决问题了。
