### ISSUE TITLE
ticket账户有钱，但是无法自动买票

### ISSUE THREAD

**Issue by chaojieli** [33cn/plugin#98]
故障描述：目前无法自动买票，区块高度在不到1W，增长开始缓慢
![_20181129143345](https://user-images.githubusercontent.com/42457452/49203589-d1ee9600-f3e3-11e8-9461-5c9d6db8356e.png)

**Comment by 33cn** [comment]
编译的是最新版本吗？

**Comment by chaojieli** [comment]
是的 @33cn

**Comment by vipwzw** [comment]
@chain33-shg  看一下问题

**Comment by vipwzw** [comment]
没有自动补充吗？

**Comment by xies1031** [comment]
自动补充的bug是这个星期修复的，要看看他的代码是什么时候的版本，或者有没有主动把coins中的bty全部转走 @chaojieli

**Comment by chaojieli** [comment]
@chain33-shg ，有钱支付手续费的哦，1EbDHAXpoiewjPLX9uqoz38HsKqMXayZrF地址为returnAddr，1PUiGcbsccfxW3zuvHXZBJfznziph5miAo为minerAddr，是续费从1PUiGcbsccfxW3zuvHXZBJfznziph5miAo扣除。
![123](https://user-images.githubusercontent.com/42457452/49372289-1906bf00-f735-11e8-88dd-f856ef4a4079.png)

**Comment by xies1031** [comment]
@chaojieli 1PUiGcbsccfxW3zuvHXZBJfznziph5miAo这个地址的钱包，自动挖矿有打开吗？

**Comment by andyYuanFZM** [comment]
后面没有再重现，先关闭此issue，后续再观察。
