### ISSUE TITLE
社区自治规则修改建议

### ISSUE THREAD

**Issue by mdj33** [33cn/plugin#999]
1. 增加全员投票参与率和投票人员赞成率的参数设置
2. 调整删除委员会成员的规则，与新增成员保持一致
3. 投票增加同意，反对，弃权三个选项，参与度统计更透明
4. 考虑到委员会成员私钥被盗乱投票情况，兼顾效率，可以由委员会成员自己提出更换另一个地址，由委员会投票通过。如果黑客抢先更换了地址，再走删除全员投票流程。

**Comment by vipwzw** [comment]
1. 可以调整，但是可能需要进行范围的限制：参与率最低设置为 50%， 最高设置为 80%，赞成率，最低 50.1%，最高80%

**Comment by vipwzw** [comment]
3. 统计参与率的时候，计算弃权票，但是统计赞成率的时候，忽略弃权票。比如10票，4票赞成，3票反对，2票弃权，那么参与率是 90%， 赞成 4/7 反对 3/7
